import {openRecoveryDb,migrateRecovery} from "../lib/recovery-db.ts";import {currentCryptoMarketSlugs} from "../lib/complete-set.ts";import {fetchEventBySlug,summarizeBook} from "../lib/polymarket.ts";import {applyMarketFrame,parseMarketFrames,type StreamBook} from "../lib/market-stream.ts";import {simulateBuy} from "../lib/execution.ts";import {estimateVolatility,type SpotPoint} from "../lib/value-strategy.ts";import * as originalV3Strategy from "../lib/recovery-v3-original-runtime.ts";import * as v3Strategy from "../lib/recovery-v3-strategy.ts";import * as v4Strategy from "../lib/recovery-strategy.ts";
const version=process.env.RECOVERY_VERSION,strategy=version==="v3-original"?originalV3Strategy:version==="v3"?v3Strategy:v4Strategy,{chooseLateWinner,extractChainlinkPoints,isFeedFresh,isHalfwayDecisionTime,missingOpeningSides,recoveryBudgetForProbability,recoveryPolicy,sizeRecoveryBuy}=strategy;
if((process.env.TRADING_MODE||"paper")!=="paper")throw new Error("Safety lock: paper only");
const now=()=>new Date().toISOString(),sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms)),MW="wss://ws-subscriptions-clob.polymarket.com/ws/market",SW="wss://ws-live-data.polymarket.com";type Spec={slug:string;market:string;asset:"BTC"|"ETH";minutes:5|15;start:number;end:number;up:string;down:string;target?:number;delay?:number};
let running=true,ms:WebSocket|null=null,mc=false,sc=false,lm:string|null=null,ls:string|null=null,err:string|null=null;const spotSockets=new Set<WebSocket>(),spotReady=new Set<"BTC"|"ETH">(),markets=new Map<string,Spec>(),tokens=new Map<string,string>(),books=new Map<string,StreamBook>(),spots:{BTC:SpotPoint[];ETH:SpotPoint[]}={BTC:[],ETH:[]},timers=new Map<string,ReturnType<typeof setTimeout>>();function stop(){running=false;ms?.close();for(const ws of spotSockets)ws.close()}process.on("SIGINT",stop);process.on("SIGTERM",stop);migrateRecovery();
function acct(d=openRecoveryDb()){const start=(d.prepare("SELECT starting_balance FROM account WHERE id=1").get() as any).starting_balance,rows=d.prepare("SELECT * FROM positions").all() as any[];const realized=rows.reduce((s,r)=>s+Number(r.realized_pnl||0),0),deployed=rows.filter(r=>r.status==="open").reduce((s,r)=>s+Number(r.cost),0),unrealized=rows.filter(r=>r.status==="open").reduce((s,r)=>s+r.shares*r.current_price-r.cost,0);return {start,realized,deployed,unrealized,equity:start+realized+unrealized,available:start+realized-deployed}}
function snap(){const d=openRecoveryDb();try{const a=acct(d);d.prepare("INSERT INTO snapshots(equity,available_cash,deployed,realized_pnl,unrealized_pnl,captured_at) VALUES(?,?,?,?,?,?)").run(a.equity,a.available,a.deployed,a.realized,a.unrealized,now())}finally{d.close()}}
function state(){const d=openRecoveryDb();try{d.prepare("INSERT INTO stream_state(id,status,market_connected,spot_connected,last_market_message,last_spot_message,subscribed_tokens,last_error,updated_at) VALUES(1,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET status=excluded.status,market_connected=excluded.market_connected,spot_connected=excluded.spot_connected,last_market_message=excluded.last_market_message,last_spot_message=excluded.last_spot_message,subscribed_tokens=excluded.subscribed_tokens,last_error=excluded.last_error,updated_at=excluded.updated_at").run(mc&&sc?"connected":"reconnecting",mc?1:0,sc?1:0,lm,ls,tokens.size,err,now())}finally{d.close()}}
async function discover(){return (await Promise.all(currentCryptoMarketSlugs(Date.now()/1000).filter(t=>t.minutes===5).map(async t=>{try{const e=await fetchEventBySlug(t.slug),m=e.markets?.[0];if(!m||e.closed||m.closed)return null;const o=JSON.parse(m.outcomes||"[]"),ids=JSON.parse(m.clobTokenIds||"[]"),ui=o.findIndex((x:string)=>/^(up|yes)$/i.test(x)),di=o.findIndex((x:string)=>/^(down|no)$/i.test(x));if(ui<0||di<0)return null;const old=markets.get(t.slug);return {slug:t.slug,market:e.title||t.slug,asset:t.asset,minutes:t.minutes,start:t.start,end:t.start+t.minutes*60,up:ids[ui],down:ids[di],target:old?.target,delay:old?.delay} as Spec}catch{return null}}))).filter(Boolean) as Spec[]}
async function refresh(ws:WebSocket,initial=false){const found=await discover();if(!found.length)throw Error("no markets");const old=new Set(tokens.keys()),next=new Set(found.flatMap(s=>[s.up,s.down])),d=openRecoveryDb();markets.clear();tokens.clear();try{for(const s of found){const saved=d.prepare("SELECT target,target_delay FROM markets WHERE slug=?").get(s.slug) as any;if(saved?.target){s.target=saved.target;s.delay=saved.target_delay}markets.set(s.slug,s);tokens.set(s.up,s.slug);tokens.set(s.down,s.slug);d.prepare("INSERT INTO markets(slug,market,asset,minutes,start_ts,end_ts,up_token,down_token,target,target_delay,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,NULL,NULL,'active',?,?) ON CONFLICT(slug) DO UPDATE SET updated_at=excluded.updated_at").run(s.slug,s.market,s.asset,s.minutes,s.start,s.end,s.up,s.down,now(),now())}}finally{d.close()}const add=[...next].filter(x=>!old.has(x)),remove=[...old].filter(x=>!next.has(x));if(initial)ws.send(JSON.stringify({assets_ids:[...next],type:"market",custom_feature_enabled:true}));else{if(add.length)ws.send(JSON.stringify({assets_ids:add,operation:"subscribe"}));if(remove.length)ws.send(JSON.stringify({assets_ids:remove,operation:"unsubscribe"}))}console.log(`Recovery bot: ${next.size} tokens`)}
function targetsFor(asset:"BTC"|"ETH",price:number,at:number){const unix=at/1000,d=openRecoveryDb();try{for(const s of markets.values()){if(s.asset!==asset||s.target||unix<s.start||unix>s.start+12)continue;s.target=price;s.delay=unix-s.start;d.prepare("UPDATE markets SET target=?,target_delay=?,updated_at=? WHERE slug=?").run(price,s.delay,now(),s.slug);console.log(`${s.slug}: target ${price.toFixed(2)}`)}}finally{d.close()}}
function addPosition(d:any,s:Spec,outcome:"Up"|"Down",fill:any,phase:string,probability:number|null,projected:number|null,reason:string){const token=outcome==="Up"?s.up:s.down,key=`${phase}:${s.slug}:${outcome}`,stamp=now(),insert=d.prepare("INSERT OR IGNORE INTO actions(event_key,slug,market,phase,outcome,probability,requested,spent,shares,avg_price,fee,fill_ratio,projected_profit,reason,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(key,s.slug,s.market,phase,outcome,probability,fill.spent,fill.spent,fill.shares,fill.avgPrice,fill.fee,fill.fillRatio,projected,reason,stamp);if(!insert.changes)return false;d.prepare("INSERT INTO positions(token,slug,market,asset,minutes,outcome,shares,cost,current_price,realized_pnl,status,opened_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,0,'open',?,?) ON CONFLICT(token) DO UPDATE SET shares=shares+excluded.shares,cost=cost+excluded.cost,current_price=excluded.current_price,updated_at=excluded.updated_at").run(token,s.slug,s.market,s.asset,s.minutes,outcome,fill.shares,fill.spent,fill.avgPrice,stamp,stamp);return true}
function evaluate(s:Spec){
  const ub=books.get(s.up),dbk=books.get(s.down),hist=spots[s.asset];if(!ub||!dbk||!s.target||hist.length<3)return;
  const u=summarizeBook(ub),dn=summarizeBook(dbk),spot=hist.at(-1)!,elapsed=Date.now()/1000-s.start,remaining=s.end-Date.now()/1000,d=openRecoveryDb();
  try{
    d.prepare("UPDATE positions SET current_price=?,updated_at=? WHERE token=? AND status='open'").run(u.bid,now(),s.up);d.prepare("UPDATE positions SET current_price=?,updated_at=? WHERE token=? AND status='open'").run(dn.bid,now(),s.down);
    let opening=(d.prepare("SELECT * FROM actions WHERE slug=? AND phase='opening'").all(s.slug) as any[]);
    if(opening.length<2&&elapsed>=0&&elapsed<=recoveryPolicy.openingRetrySeconds){if(!recoveryPolicy.independentOpening){if(opening.length)return;const a=acct(d),needed=recoveryPolicy.openingDollarsPerSide*2;if(a.equity<recoveryPolicy.minimumEquityToTrade||a.available<needed||a.deployed+needed>recoveryPolicy.maxPortfolioExposure)return;const uf=simulateBuy(ub,recoveryPolicy.openingDollarsPerSide),df=simulateBuy(dbk,recoveryPolicy.openingDollarsPerSide),worstCaseProfit=Math.min(uf.shares,df.shares)-uf.spent-df.spent;if(uf.fillRatio>=recoveryPolicy.minimumFillRatio&&df.fillRatio>=recoveryPolicy.minimumFillRatio&&worstCaseProfit>=-recoveryPolicy.maxOpeningWorstCaseLoss){addPosition(d,s,"Up",uf,"opening",null,null,`Atomic equal-dollar opening pair; worst-case settlement ${worstCaseProfit.toFixed(2)}`);addPosition(d,s,"Down",df,"opening",null,null,`Atomic equal-dollar opening pair; worst-case settlement ${worstCaseProfit.toFixed(2)}`);console.log(`${s.slug}: opened atomic $${recoveryPolicy.openingDollarsPerSide} Up + $${recoveryPolicy.openingDollarsPerSide} Down`);snap()}return}let changed=false;for(const side of missingOpeningSides(opening)){const a=acct(d);if(a.equity<recoveryPolicy.minimumEquityToTrade||a.available<recoveryPolicy.openingDollarsPerSide||a.deployed+recoveryPolicy.openingDollarsPerSide>recoveryPolicy.maxPortfolioExposure)break;const fill=simulateBuy(side==="Up"?ub:dbk,recoveryPolicy.openingDollarsPerSide);if(fill.fillRatio<recoveryPolicy.minimumFillRatio)continue;if(addPosition(d,s,side,fill,"opening",null,null,opening.length?"Missing opening leg recovered from refreshed visible depth":"Independent equal-dollar opening leg")){changed=true;opening.push({outcome:side});console.log(`${s.slug}: opened ${side} $${fill.spent.toFixed(2)}`)}}if(changed)snap();return}
    if(opening.length<2)return;
    if(isHalfwayDecisionTime(s.minutes,elapsed)&&!d.prepare("SELECT slug FROM decisions WHERE slug=?").get(s.slug)){
      const window=hist.filter(x=>x.at>=spot.at-150000),sigma=estimateVolatility(window),choice=chooseLateWinner({current:spot.price,target:s.target,secondsRemaining:remaining,sigmaPerRootSecond:sigma}),positions=d.prepare("SELECT * FROM positions WHERE slug=? AND status='open'").all(s.slug) as any[],winner=positions.find(p=>p.outcome===choice.side),cost=positions.reduce((z,p)=>z+p.cost,0),a=acct(d),book=choice.side==="Up"?ub:dbk;
      const riskCash=Math.max(0,Math.min(a.available,recoveryPolicy.maxPortfolioExposure-a.deployed)),sized=choice.probability<recoveryPolicy.minimumWinnerProbability?{action:"skip" as const,reason:`Halfway confidence ${(choice.probability*100).toFixed(1)}% was below ${(recoveryPolicy.minimumWinnerProbability*100).toFixed(0)}%`}:sizeRecoveryBuy({book,existingWinnerShares:winner?.shares||0,totalMarketCost:cost,availableCash:riskCash,currentMarketCost:cost,maxAdditionalDollars:recoveryBudgetForProbability(choice.probability),modelProbability:choice.probability});let action="decision_no_add",reason=sized.reason,projected:null|number=null;
      if(sized.action==="buy"){addPosition(d,s,choice.side,sized.fill,"recovery",choice.probability,sized.projectedProfit,sized.reason);action="paper_recovery_buy";projected=sized.projectedProfit;console.log(`${s.slug}: halfway choice ${choice.side}, recovery $${sized.fill.spent.toFixed(2)}`)}
      d.prepare("INSERT INTO decisions(slug,winner,probability,up_probability,spot,target,seconds_remaining,volatility,action,reason,projected_profit,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").run(s.slug,choice.side,choice.probability,choice.upProbability,spot.price,s.target,remaining,sigma,action,reason,projected,now());snap()
    }
    const upProbability=(u.bid+u.ask)/2,downProbability=(dn.bid+dn.ask)/2,lateProbability=Math.max(upProbability,downProbability),lateSide=(upProbability>=downProbability?"Up":"Down") as "Up"|"Down";
    if(recoveryPolicy.lateConfirmationEnabled&&elapsed>=recoveryPolicy.observationSeconds&&remaining>20&&lateProbability>recoveryPolicy.lateMarketProbability&&!d.prepare("SELECT id FROM actions WHERE slug=? AND phase='late85'").get(s.slug)){
      const positions=d.prepare("SELECT * FROM positions WHERE slug=? AND status='open'").all(s.slug) as any[],winner=positions.find(p=>p.outcome===lateSide),cost=positions.reduce((z,p)=>z+p.cost,0),a=acct(d),book=lateSide==="Up"?ub:dbk;
      const sized=sizeRecoveryBuy({book,existingWinnerShares:winner?.shares||0,totalMarketCost:cost,availableCash:Math.max(0,Math.min(a.available,recoveryPolicy.maxPortfolioExposure-a.deployed)),currentMarketCost:cost,maxAdditionalDollars:recoveryPolicy.maxLateAddDollars,modelProbability:lateProbability});
      if(sized.action==="buy"){
        const reason=`Polymarket ${lateSide} midpoint ${(lateProbability*100).toFixed(1)}% exceeded 85%. ${sized.reason}`;addPosition(d,s,lateSide,sized.fill,"late85",lateProbability,sized.projectedProfit,reason);console.log(`${s.slug}: 85% confirmation ${lateSide}, added $${sized.fill.spent.toFixed(2)}`)
      }else{
        d.prepare("INSERT OR IGNORE INTO actions(event_key,slug,market,phase,outcome,probability,requested,spent,shares,avg_price,fee,fill_ratio,projected_profit,reason,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(`late85:${s.slug}:${lateSide}`,s.slug,s.market,"late85",lateSide,lateProbability,0,0,0,0,0,0,null,`Polymarket ${lateSide} midpoint ${(lateProbability*100).toFixed(1)}% exceeded 85%, but no add: ${sized.reason}`,now());
      }
      snap()
    }
  }finally{d.close()}
}
function schedule(slug:string){const old=timers.get(slug);if(old)clearTimeout(old);timers.set(slug,setTimeout(()=>{timers.delete(slug);const s=markets.get(slug);if(s)evaluate(s)},50))}
async function settle(){const candidates=(()=>{const d=openRecoveryDb();try{return d.prepare("SELECT * FROM markets WHERE status='active' AND end_ts<?").all(Date.now()/1000-5) as any[]}finally{d.close()}})();for(const s of candidates){try{const e=await fetchEventBySlug(s.slug),m=e.markets?.[0];if(!e.closed||!m?.closed)continue;const ids=JSON.parse(m.clobTokenIds||"[]"),prices=JSON.parse(m.outcomePrices||"[]"),d=openRecoveryDb();try{for(const p of d.prepare("SELECT * FROM positions WHERE slug=? AND status='open'").all(s.slug) as any[]){const i=ids.indexOf(p.token),final=Number(prices[i]);if(i<0||(final!==0&&final!==1))continue;d.prepare("UPDATE positions SET shares=0,cost=0,current_price=?,realized_pnl=realized_pnl+?,status=?,updated_at=?,closed_at=? WHERE token=?").run(final,p.shares*final-p.cost,final===1?"won":"lost",now(),now(),p.token)}d.prepare("UPDATE markets SET status='resolved',updated_at=? WHERE slug=?").run(now(),s.slug)}finally{d.close()}}catch{}}snap()}
async function marketLoop(){
  let back=1000;
  while(running){
    try{
      await new Promise<void>((_,reject)=>{
        const ws=new WebSocket(MW);ms=ws;let rt:any,hb:any;
        ws.onopen=async()=>{try{back=1000;await refresh(ws,true);mc=true;err=null;state();rt=setInterval(()=>{void refresh(ws).catch(e=>{err=e instanceof Error?e.message:String(e);state()})},15000);hb=setInterval(()=>ws.readyState===WebSocket.OPEN&&ws.send("PING"),10000)}catch(e){reject(e)}};
        ws.onmessage=e=>{lm=now();if(e.data!=="PONG")for(const f of parseMarketFrames(String(e.data)))for(const token of applyMarketFrame(books,f)){const slug=tokens.get(token);if(slug)schedule(slug)}};
        ws.onerror=()=>err="market feed error";
        ws.onclose=()=>{clearInterval(rt);clearInterval(hb);mc=false;state();reject(Error("closed"))}
      });
      back=1000
    }catch{await sleep(back);back=Math.min(30000,back*2)}
  }
}
async function spotLoop(){
  let back=1000;
  while(running){
    try{
      await new Promise<void>((_,reject)=>{
        const ws=new WebSocket(SW);spotSockets.add(ws);let hb:any,watchdog:any;const openedAt=Date.now(),lastReceived:{BTC:number;ETH:number}={BTC:0,ETH:0};
        ws.onopen=()=>{
          back=1000;
          spotReady.clear();sc=false;err=null;state();
          ws.send(JSON.stringify({action:"subscribe",subscriptions:[{topic:"crypto_prices_chainlink",type:"update"}]}));
          hb=setInterval(()=>ws.readyState===WebSocket.OPEN&&ws.send("PING"),10000);
          watchdog=setInterval(()=>{const stale=(Object.keys(lastReceived) as ("BTC"|"ETH")[]).filter(asset=>!isFeedFresh(lastReceived[asset]||openedAt,Date.now()));if(stale.length){err=`${stale.join(" and ")} Chainlink feed stale for more than 30 seconds; reconnecting`;for(const asset of stale)spotReady.delete(asset);sc=false;state();console.warn(err);ws.close(4000,"stale spot feed")}},5000)
        };
        ws.onmessage=e=>{if(e.data==="PONG")return;try{const payload=JSON.parse(String(e.data)).payload||{},points=extractChainlinkPoints(payload);if(!points.length)return;ls=now();err=null;for(const {asset,price,at} of points){lastReceived[asset]=Date.now();spotReady.add(asset);spots[asset]=[...spots[asset],{at,price}].filter(x=>x.at>=at-180000);targetsFor(asset,price,at);for(const s of markets.values())if(s.asset===asset)schedule(s.slug)}sc=spotReady.size===2}catch{}};
        ws.onerror=()=>err="spot feed error";
        ws.onclose=()=>{clearInterval(hb);clearInterval(watchdog);spotSockets.delete(ws);spotReady.clear();sc=false;state();reject(Error("closed"))}
      });
      back=1000
    }catch{await sleep(back);back=Math.min(30000,back*2)}
  }
}
setInterval(()=>{state();snap();void settle()},10000);snap();await Promise.all([marketLoop(),spotLoop()]);
