import {openRecoveryDb,migrateRecovery} from "../lib/recovery-db.ts";
import {currentCryptoMarketSlugs,simulateCompleteSet} from "../lib/complete-set.ts";
import {fetchBook,fetchEventBySlug,summarizeBook} from "../lib/polymarket.ts";
import {applyMarketFrame,hasUsableAskDepth,parseMarketFrames,type StreamBook} from "../lib/market-stream.ts";
import {simulateBuy,simulateSell} from "../lib/execution.ts";
import {estimateVolatility,probabilityAboveTarget,type SpotPoint} from "../lib/value-strategy.ts";
import {extractChainlinkPoints,isFeedFresh} from "../lib/recovery-strategy.ts";
import {decideSelectiveV5Entry,selectiveV5Policy} from "../lib/v5-selective-strategy.ts";
import {currentDecisionPrice,timeWeightedAverage} from "../lib/v5-selective-strategy.ts";
import {chooseDynamicManagement,choosePostExitReversal,chooseScaledV53Management,chooseScaledV53PostExit,dynamicUpProbability,dynamicV51Policy,scaledV53Policy,scaledV53Stake} from "../lib/v51-dynamic-strategy.ts";
import fs from "node:fs";
import path from "node:path";

if((process.env.TRADING_MODE||"paper")!=="paper")throw new Error("Safety lock: TRADING_MODE must equal paper");
const IS_V53=process.env.V53_SCALED==="1",IS_V52=process.env.V52_DYNAMIC==="1"||IS_V53,IS_V51=process.env.V51_DYNAMIC==="1"||IS_V52,DB=IS_V53?"v53-scaled.db":IS_V52?"v52-dynamic.db":IS_V51?"v51-dynamic.db":"v5-selective.db",LABEL=IS_V53?"V5.3 Scaled Active · BTC 5m":IS_V52?"V5.2 Active Dynamic Value · BTC 5m":IS_V51?"V5.1 Dynamic Value · BTC 5m":"Selective Value V5 · BTC 5m only",MARKET_WS="wss://ws-subscriptions-clob.polymarket.com/ws/market",SPOT_WS="wss://ws-live-data.polymarket.com",PID_FILE=path.join(process.cwd(),"data",IS_V53?"v53-scaled.pid":IS_V52?"v52-dynamic.pid":IS_V51?"v51-dynamic.pid":"v5-selective.pid");
const now=()=>new Date().toISOString(),sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
type Spec={slug:string;market:string;asset:"BTC";minutes:5;start:number;end:number;up:string;down:string;target?:number;targetDelay?:number};
let running=true,marketSocket:WebSocket|null=null,marketConnected=false,spotConnected=false,lastMarket:string|null=null,lastSpot:string|null=null,lastError:string|null=null;
const spotSockets=new Set<WebSocket>(),spotReady=new Set<"BTC">(),markets=new Map<string,Spec>(),tokens=new Map<string,string>(),books=new Map<string,StreamBook>(),spots:{BTC:SpotPoint[]}={BTC:[]},timers=new Map<string,ReturnType<typeof setTimeout>>(),bookRecoveries=new Set<string>(),lastBookRecovery=new Map<string,number>();
function acquireSingleInstance(){fs.mkdirSync(path.dirname(PID_FILE),{recursive:true});for(let attempt=0;attempt<2;attempt++){try{fs.writeFileSync(PID_FILE,String(process.pid),{flag:"wx"});return}catch(error:any){if(error?.code!=="EEXIST")throw error;const prior=Number(fs.readFileSync(PID_FILE,"utf8"));try{process.kill(prior,0);throw new Error(`Selective V5 is already running as process ${prior}`)}catch(check:any){if(check?.message?.startsWith("Selective V5"))throw check;fs.unlinkSync(PID_FILE)}}}throw new Error("Could not acquire Selective V5 process lock")}
function releaseSingleInstance(){try{if(Number(fs.readFileSync(PID_FILE,"utf8"))===process.pid)fs.unlinkSync(PID_FILE)}catch{}}
acquireSingleInstance();process.on("exit",releaseSingleInstance);
function stop(){running=false;marketSocket?.close();for(const ws of spotSockets)ws.close();for(const timer of timers.values())clearTimeout(timer);releaseSingleInstance();setTimeout(()=>process.exit(0),100).unref()}
process.on("SIGINT",stop);process.on("SIGTERM",stop);
migrateRecovery(DB,LABEL);
{const d=openRecoveryDb(DB);try{d.prepare("UPDATE account SET strategy=? WHERE id=1 AND NOT EXISTS (SELECT 1 FROM actions)").run(LABEL)}finally{d.close()}}

function db(){return openRecoveryDb(DB)}
function account(d=db()){const start=(d.prepare("SELECT starting_balance FROM account WHERE id=1").get() as any).starting_balance,rows=d.prepare("SELECT * FROM positions").all() as any[];const realized=rows.reduce((s,r)=>s+Number(r.realized_pnl||0),0),deployed=rows.filter(r=>r.status==="open").reduce((s,r)=>s+Number(r.cost),0),unrealized=rows.filter(r=>r.status==="open").reduce((s,r)=>s+Number(r.shares)*Number(r.current_price)-Number(r.cost),0);return {start,realized,deployed,unrealized,equity:start+realized+unrealized,available:start+realized-deployed}}
function snapshot(){const d=db();try{const a=account(d);d.prepare("INSERT INTO snapshots(equity,available_cash,deployed,realized_pnl,unrealized_pnl,captured_at) VALUES(?,?,?,?,?,?)").run(a.equity,a.available,a.deployed,a.realized,a.unrealized,now())}finally{d.close()}}
function state(){const d=db();try{d.prepare("INSERT INTO stream_state(id,status,market_connected,spot_connected,last_market_message,last_spot_message,subscribed_tokens,last_error,updated_at) VALUES(1,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET status=excluded.status,market_connected=excluded.market_connected,spot_connected=excluded.spot_connected,last_market_message=excluded.last_market_message,last_spot_message=excluded.last_spot_message,subscribed_tokens=excluded.subscribed_tokens,last_error=excluded.last_error,updated_at=excluded.updated_at").run(marketConnected&&spotConnected?"connected":"reconnecting",marketConnected?1:0,spotConnected?1:0,lastMarket,lastSpot,tokens.size,lastError,now())}finally{d.close()}}

function inDecisionWindow(s:Spec){const remaining=s.end-Date.now()/1000;return remaining>=selectiveV5Policy.decisionEndSecondsRemaining&&remaining<=selectiveV5Policy.decisionStartSecondsRemaining}
function recordDataWait(s:Spec,reason:string){if(!IS_V53||!inDecisionWindow(s))return;const point=spots.BTC.at(-1),remaining=s.end-Date.now()/1000,d=db();try{d.prepare("INSERT INTO decisions(slug,winner,probability,up_probability,spot,target,seconds_remaining,volatility,action,reason,projected_profit,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,NULL,?) ON CONFLICT(slug) DO UPDATE SET seconds_remaining=excluded.seconds_remaining,action=excluded.action,reason=excluded.reason,created_at=excluded.created_at WHERE decisions.action NOT LIKE 'paper_%'").run(s.slug,"Unavailable",.5,.5,point?.price||0,s.target||0,remaining,0,"data_wait",reason,now())}finally{d.close()}}
async function recoverBooks(s:Spec){if(!IS_V53||bookRecoveries.has(s.slug)||Date.now()-(lastBookRecovery.get(s.slug)||0)<2000)return;bookRecoveries.add(s.slug);lastBookRecovery.set(s.slug,Date.now());try{const [up,down]=await Promise.all([fetchBook(s.up),fetchBook(s.down)]);books.set(s.up,up);books.set(s.down,down);lastError=null;schedule(s.slug)}catch(error){lastError=`Order-book recovery failed: ${error instanceof Error?error.message:String(error)}`;state()}finally{bookRecoveries.delete(s.slug)}}

async function discover(){return (await Promise.all(currentCryptoMarketSlugs(Date.now()/1000).filter(t=>t.minutes===5&&t.asset==="BTC").map(async t=>{try{const e=await fetchEventBySlug(t.slug),m=e.markets?.[0];if(!m||e.closed||m.closed)return null;const outcomes=JSON.parse(m.outcomes||"[]"),ids=JSON.parse(m.clobTokenIds||"[]"),ui=outcomes.findIndex((x:string)=>/^(up|yes)$/i.test(x)),di=outcomes.findIndex((x:string)=>/^(down|no)$/i.test(x));if(ui<0||di<0)return null;const old=markets.get(t.slug);return {slug:t.slug,market:e.title||t.slug,asset:t.asset,minutes:5,start:t.start,end:t.start+300,up:ids[ui],down:ids[di],target:old?.target,targetDelay:old?.targetDelay} as Spec}catch(e){lastError=e instanceof Error?e.message:String(e);return null}}))).filter(Boolean) as Spec[]}
async function refresh(ws:WebSocket,initial=false){const found=await discover();if(!found.length)throw new Error("No current BTC five-minute market");const old=new Set(tokens.keys()),next=new Set(found.flatMap(s=>[s.up,s.down])),d=db();markets.clear();tokens.clear();try{for(const s of found){const saved=d.prepare("SELECT target,target_delay FROM markets WHERE slug=?").get(s.slug) as any;if(saved?.target){s.target=Number(saved.target);s.targetDelay=Number(saved.target_delay)}markets.set(s.slug,s);tokens.set(s.up,s.slug);tokens.set(s.down,s.slug);d.prepare("INSERT INTO markets(slug,market,asset,minutes,start_ts,end_ts,up_token,down_token,target,target_delay,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,NULL,NULL,'active',?,?) ON CONFLICT(slug) DO UPDATE SET updated_at=excluded.updated_at").run(s.slug,s.market,s.asset,s.minutes,s.start,s.end,s.up,s.down,now(),now())}}finally{d.close()}const add=[...next].filter(x=>!old.has(x)),remove=[...old].filter(x=>!next.has(x));if(initial)ws.send(JSON.stringify({assets_ids:[...next],type:"market",custom_feature_enabled:true}));else{if(add.length)ws.send(JSON.stringify({assets_ids:add,operation:"subscribe"}));if(remove.length)ws.send(JSON.stringify({assets_ids:remove,operation:"unsubscribe"}))}if(IS_V53)for(const s of found)if(add.includes(s.up)||add.includes(s.down)||!hasUsableAskDepth(books.get(s.up))||!hasUsableAskDepth(books.get(s.down)))void recoverBooks(s);console.log(`Selective V5: ${next.size} outcome tokens`)}
function captureTargets(asset:"BTC",at:number){const unix=at/1000,d=db();try{for(const s of markets.values()){if(s.asset!==asset||s.target||unix<s.start||unix>s.start+selectiveV5Policy.maximumTargetDelaySeconds)continue;const twap=timeWeightedAverage(spots.BTC,s.start*1000);if(twap<=0)continue;s.target=twap;s.targetDelay=unix-s.start;d.prepare("UPDATE markets SET target=?,target_delay=?,updated_at=? WHERE slug=?").run(twap,s.targetDelay,now(),s.slug);console.log(`${s.slug}: Chainlink 60s TWAP target ${twap.toFixed(2)} at +${s.targetDelay.toFixed(1)}s`)}}finally{d.close()}}
function addPosition(d:any,s:Spec,outcome:"Up"|"Down",phase:string,spent:number,shares:number,avgPrice:number,fee:number,probability:number|null,reason:string,projected:number|null=null){const token=outcome==="Up"?s.up:s.down,stamp=now(),result=d.prepare("INSERT OR IGNORE INTO actions(event_key,slug,market,phase,outcome,probability,requested,spent,shares,avg_price,fee,fill_ratio,projected_profit,reason,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(`${phase}:${s.slug}:${outcome}`,s.slug,s.market,phase,outcome,probability,spent,spent,shares,avgPrice,fee,1,projected,reason,stamp);if(!result.changes)return false;d.prepare("INSERT INTO positions(token,slug,market,asset,minutes,outcome,shares,cost,current_price,realized_pnl,status,opened_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,0,'open',?,?)").run(token,s.slug,s.market,s.asset,s.minutes,outcome,shares,spent,avgPrice,stamp,stamp);return true}

function manageV51(d:any,s:Spec,existing:any[],upBook:StreamBook,downBook:StreamBook,upProbability:number,underlyingUpProbability:number){
  if(!IS_V51||existing.length!==1)return false;
  const held=existing[0],heldBook=held.outcome==="Up"?upBook:downBook,oppositeBook=held.outcome==="Up"?downBook:upBook,sell=simulateSell(heldBook,held.shares),opposite=simulateBuy(oppositeBook,IS_V53?scaledV53Policy.reversalBudget:dynamicV51Policy.hedgeBudget);
  const decision=IS_V53?chooseScaledV53Management({heldSide:held.outcome,shares:held.shares,cost:held.cost,upProbability,underlyingUpProbability,sellProceeds:sell.proceeds,oppositeShares:opposite.shares,oppositeSpend:opposite.spent,secondsRemaining:s.end-Date.now()/1000,heldSeconds:(Date.now()-Date.parse(held.opened_at))/1000}):chooseDynamicManagement({heldSide:held.outcome,shares:held.shares,cost:held.cost,upProbability,sellProceeds:sell.proceeds,oppositeShares:opposite.shares,oppositeSpend:opposite.spent});
  if((decision.action==="sell"||decision.action==="flip")&&sell.fillRatio>=dynamicV51Policy.minimumFillRatio){const stamp=now(),pnl=sell.proceeds-held.cost;d.prepare("INSERT OR IGNORE INTO actions(event_key,slug,market,phase,outcome,probability,requested,spent,shares,avg_price,fee,fill_ratio,projected_profit,reason,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(`dynamic_exit:${s.slug}:${held.outcome}`,s.slug,s.market,"dynamic_exit",held.outcome,held.outcome==="Up"?upProbability:1-upProbability,held.shares,sell.proceeds,sell.shares,sell.avgPrice,sell.fee,sell.fillRatio,pnl,decision.reason,stamp);d.prepare("UPDATE positions SET shares=0,cost=0,current_price=?,realized_pnl=realized_pnl+?,status='sold',updated_at=?,closed_at=? WHERE token=?").run(sell.avgPrice,pnl,stamp,stamp,held.token);if(decision.action==="flip"&&opposite.fillRatio>=dynamicV51Policy.minimumFillRatio)return addPosition(d,s,held.outcome==="Up"?"Down":"Up","dynamic_flip",opposite.spent,opposite.shares,opposite.avgPrice,opposite.fee,held.outcome==="Up"?1-upProbability:upProbability,decision.reason,decision.oppositeExpectedProfit);return true}
  if(!IS_V53&&decision.action==="hedge"&&opposite.fillRatio>=dynamicV51Policy.minimumFillRatio){return addPosition(d,s,held.outcome==="Up"?"Down":"Up","dynamic_hedge",opposite.spent,opposite.shares,opposite.avgPrice,opposite.fee,held.outcome==="Up"?1-upProbability:upProbability,decision.reason,decision.after.worst)}
  return false;
}

function evaluate(s:Spec){const upBook=books.get(s.up),downBook=books.get(s.down),history=spots.BTC;if(!hasUsableAskDepth(upBook)||!hasUsableAskDepth(downBook)){recordDataWait(s,"Waiting for usable Up and Down order-book depth; REST recovery requested");void recoverBooks(s);return}if(!s.target){recordDataWait(s,"Opening Chainlink target was unavailable");return}if(history.length<3){recordDataWait(s,"Insufficient Chainlink observations");return}const up=summarizeBook(upBook!),down=summarizeBook(downBook!),point=history.at(-1)!,currentTwap=currentDecisionPrice(history,point.at),remaining=s.end-Date.now()/1000;if(currentTwap<=0){recordDataWait(s,"No valid Chainlink decision price was available");return}const d=db();try{
  if(up.bid>0)d.prepare("UPDATE positions SET current_price=?,updated_at=? WHERE token=? AND status='open'").run(up.bid,now(),s.up);if(down.bid>0)d.prepare("UPDATE positions SET current_price=?,updated_at=? WHERE token=? AND status='open'").run(down.bid,now(),s.down);
  const existing=d.prepare("SELECT * FROM positions WHERE slug=? AND status='open'").all(s.slug) as any[];
  const recent=history.find(x=>x.at>=point.at-30_000),momentum=recent&&recent.price>0?point.price/recent.price-1:0,upBidDepth=upBook.bids.reduce((sum,x)=>sum+Number(x.size),0),upAskDepth=upBook.asks.reduce((sum,x)=>sum+Number(x.size),0),managementSigma=estimateVolatility(history.filter(x=>x.at>=point.at-240_000));
  const baseUp=probabilityAboveTarget(currentTwap,s.target,Math.max(1,remaining),managementSigma),dynamicUp=dynamicUpProbability(baseUp,momentum,upBidDepth,upAskDepth);
  if(existing.length){if(manageV51(d,s,existing,upBook,downBook,dynamicUp,baseUp))snapshot();return}
  const today=now().slice(0,10),daily=Number((d.prepare("SELECT COALESCE(SUM(realized_pnl),0) p FROM positions WHERE closed_at LIKE ?").get(`${today}%`) as any).p);
  if(IS_V53&&(daily>=scaledV53Policy.dailyProfitTarget||daily<=-scaledV53Policy.dailyLossStop))return;
  if(IS_V52){const sold=d.prepare("SELECT * FROM positions WHERE slug=? AND status='sold' ORDER BY closed_at DESC LIMIT 1").get(s.slug) as any;if(sold){const oppositeBook=sold.outcome==="Up"?downBook:upBook,fill=simulateBuy(oppositeBook,IS_V53?scaledV53Policy.reversalBudget:dynamicV51Policy.hedgeBudget),reversal=IS_V53?chooseScaledV53PostExit({soldSide:sold.outcome,upProbability:dynamicUp,oppositeShares:fill.shares,oppositeSpend:fill.spent,secondsRemaining:remaining}):choosePostExitReversal({soldSide:sold.outcome,upProbability:dynamicUp,oppositeShares:fill.shares,oppositeSpend:fill.spent,secondsRemaining:remaining});if(reversal.action==="reverse"&&fill.fillRatio>=dynamicV51Policy.minimumFillRatio&&addPosition(d,s,reversal.side,"dynamic_reversal",fill.spent,fill.shares,fill.avgPrice,fill.fee,reversal.probability,reversal.reason,reversal.expectedProfit)){snapshot()}return}}
  const a=account(d);if(a.available<5||a.deployed>=selectiveV5Policy.maximumOpenExposure)return;
  const pairPolicy={minNetEdgePerPair:.015,executionBufferPerPair:.005,minLockedProfit:.25,maxDollarsPerMarket:selectiveV5Policy.maximumCompleteSetSpend},pair=simulateCompleteSet(upBook,downBook,Math.min(a.available,selectiveV5Policy.maximumCompleteSetSpend),pairPolicy);
  if(pair.decision==="paper_complete_set"&&a.deployed+pair.spent<=selectiveV5Policy.maximumOpenExposure){const reason=`Equal-share complete set: ${pair.reason}`;addPosition(d,s,"Up","complete_set",pair.upGross+pair.upFees,pair.pairs,pair.upGross/pair.pairs,pair.upFees,null,reason,pair.lockedProfit);addPosition(d,s,"Down","complete_set",pair.downGross+pair.downFees,pair.pairs,pair.downGross/pair.pairs,pair.downFees,null,reason,pair.lockedProfit);d.prepare("INSERT INTO decisions(slug,winner,probability,up_probability,spot,target,seconds_remaining,volatility,action,reason,projected_profit,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(slug) DO UPDATE SET action=excluded.action,reason=excluded.reason,projected_profit=excluded.projected_profit,created_at=excluded.created_at").run(s.slug,"Both",1,.5,point.price,s.target,remaining,0,"paper_complete_set",reason,pair.lockedProfit,now());console.log(`${s.slug}: locked complete set $${pair.lockedProfit.toFixed(2)}`);snapshot();return}
  const window=history.filter(x=>x.at>=Math.max(s.start*1000-60_000,point.at-240000)),historySeconds=(point.at-s.start*1000)/1000,sigma=estimateVolatility(window);const decision=decideSelectiveV5Entry({asset:s.asset,secondsRemaining:remaining,targetDelaySeconds:s.targetDelay||0,historySeconds,current:currentTwap,target:s.target,sigmaPerRootSecond:sigma,upAsk:up.ask,downAsk:down.ask,upSpread:up.spread,downSpread:down.spread,availableCash:a.available,openExposure:a.deployed,dailyRealizedPnl:daily});
  let action="observe",reason=decision.reason,winner:"Up"|"Down"=currentTwap>=s.target?"Up":"Down",probability=.5,upProbability=.5,projected:null|number=null;
  if("probability" in decision){winner=decision.side;probability=decision.probability;upProbability=decision.upProbability}
  if(decision.action==="paper_buy"){winner=IS_V51?(dynamicUp>=.5?"Up":"Down"):decision.side;upProbability=IS_V51?dynamicUp:decision.upProbability;probability=winner==="Up"?upProbability:1-upProbability;const book=winner==="Up"?upBook:downBook,budget=IS_V53?scaledV53Stake(probability):decision.dollars,fill=simulateBuy(book,budget),actualNetEdge=probability-fill.avgPrice-(fill.shares?fill.fee/fill.shares:1)-selectiveV5Policy.executionReservePerShare,required=IS_V52?-1:IS_V51?dynamicV51Policy.minimumEntryEdge:decision.minimumNetEdge;if(fill.fillRatio>=selectiveV5Policy.minimumFillRatio&&fill.spent>=5&&actualNetEdge>=required){reason=`${IS_V53?`Scaled ${budget.toFixed(0)} dollar`:IS_V51?"Dynamic":"Selective"} momentum/order-flow signal; ${(actualNetEdge*100).toFixed(1)}pp executable edge; ${(fill.fillRatio*100).toFixed(0)}% visible-depth fill`;projected=fill.shares-fill.spent;if(addPosition(d,s,winner,"directional",fill.spent,fill.shares,fill.avgPrice,fill.fee,probability,reason,projected)){action="paper_directional_buy";console.log(`${s.slug}: ${IS_V53?"scaled V5.3":IS_V52?"active V5.2":IS_V51?"dynamic V5.1":"selective"} ${winner} $${fill.spent.toFixed(2)}, net edge ${(actualNetEdge*100).toFixed(1)}pp`)}}else reason=`Signal rejected after walking visible depth: ${(actualNetEdge*100).toFixed(1)}pp executable edge versus ${(required*100).toFixed(1)}pp required`}
  d.prepare("INSERT INTO decisions(slug,winner,probability,up_probability,spot,target,seconds_remaining,volatility,action,reason,projected_profit,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(slug) DO UPDATE SET winner=excluded.winner,probability=excluded.probability,up_probability=excluded.up_probability,spot=excluded.spot,target=excluded.target,seconds_remaining=excluded.seconds_remaining,volatility=excluded.volatility,action=excluded.action,reason=excluded.reason,projected_profit=excluded.projected_profit,created_at=excluded.created_at WHERE decisions.action NOT LIKE 'paper_%' AND (decisions.seconds_remaining NOT BETWEEN ? AND ? OR excluded.seconds_remaining BETWEEN ? AND ?)").run(s.slug,winner,probability,upProbability,currentTwap,s.target,remaining,sigma,action,reason,projected,now(),selectiveV5Policy.decisionEndSecondsRemaining,selectiveV5Policy.decisionStartSecondsRemaining,selectiveV5Policy.decisionEndSecondsRemaining,selectiveV5Policy.decisionStartSecondsRemaining);if(action.startsWith("paper_"))snapshot()
}finally{d.close()}}
function schedule(slug:string){const old=timers.get(slug);if(old)clearTimeout(old);timers.set(slug,setTimeout(()=>{timers.delete(slug);const s=markets.get(slug);if(s)evaluate(s)},25))}
async function settle(){const candidates=(()=>{const d=db();try{return d.prepare("SELECT * FROM markets WHERE status='active' AND end_ts<?").all(Date.now()/1000-5) as any[]}finally{d.close()}})();for(const s of candidates){try{const e=await fetchEventBySlug(s.slug),m=e.markets?.[0];if(!e.closed||!m?.closed)continue;const ids=JSON.parse(m.clobTokenIds||"[]"),prices=JSON.parse(m.outcomePrices||"[]"),d=db();try{for(const p of d.prepare("SELECT * FROM positions WHERE slug=? AND status='open'").all(s.slug) as any[]){const i=ids.indexOf(p.token),final=Number(prices[i]);if(i<0||(final!==0&&final!==1))continue;d.prepare("UPDATE positions SET shares=0,cost=0,current_price=?,realized_pnl=realized_pnl+?,status=?,updated_at=?,closed_at=? WHERE token=?").run(final,p.shares*final-p.cost,final===1?"won":"lost",now(),now(),p.token)}d.prepare("UPDATE markets SET status='resolved',updated_at=? WHERE slug=?").run(now(),s.slug)}finally{d.close()}}catch(e){lastError=e instanceof Error?e.message:String(e)}}snapshot()}
async function marketLoop(){let backoff=1000;while(running){try{await new Promise<void>((_,reject)=>{const ws=new WebSocket(MARKET_WS);marketSocket=ws;let refreshTimer:any,heartbeat:any;ws.onopen=async()=>{try{backoff=1000;await refresh(ws,true);marketConnected=true;lastError=null;state();refreshTimer=setInterval(()=>void refresh(ws).catch(e=>{lastError=e instanceof Error?e.message:String(e);state()}),5000);heartbeat=setInterval(()=>ws.readyState===WebSocket.OPEN&&ws.send("PING"),10000)}catch(e){reject(e)}};ws.onmessage=e=>{lastMarket=now();if(e.data!=="PONG")for(const frame of parseMarketFrames(String(e.data)))for(const token of applyMarketFrame(books,frame)){const slug=tokens.get(token);if(slug)schedule(slug)}};ws.onerror=()=>{lastError="Market WebSocket error";console.warn(lastError)};ws.onclose=e=>{clearInterval(refreshTimer);clearInterval(heartbeat);marketConnected=false;lastError=`Market WebSocket closed (${e.code}${e.reason?`: ${e.reason}`:""})`;console.warn(lastError);state();reject(new Error(lastError))}});backoff=1000}catch{await sleep(backoff);backoff=Math.min(30000,backoff*2)}}}
async function spotLoop(){let backoff=1000;while(running){try{await new Promise<void>((_,reject)=>{const ws=new WebSocket(SPOT_WS);spotSockets.add(ws);let heartbeat:any,watchdog:any;const opened=Date.now(),received:{BTC:number}={BTC:0};ws.onopen=()=>{backoff=1000;spotReady.clear();spotConnected=false;lastError=null;state();ws.send(JSON.stringify({action:"subscribe",subscriptions:[{topic:"crypto_prices_chainlink",type:"update"}]}));heartbeat=setInterval(()=>ws.readyState===WebSocket.OPEN&&ws.send("PING"),10000);watchdog=setInterval(()=>{if(!isFeedFresh(received.BTC||opened,Date.now())){lastError="BTC Chainlink feed stale";spotConnected=false;state();ws.close(4000,"stale")}},5000)};ws.onmessage=e=>{if(e.data==="PONG")return;try{const payload=JSON.parse(String(e.data)).payload||{},points=extractChainlinkPoints(payload).filter(point=>point.asset==="BTC");if(!points.length)return;lastSpot=now();lastError=null;for(const {price,at} of points){received.BTC=Date.now();spotReady.add("BTC");spots.BTC=[...spots.BTC,{at,price}].filter(x=>x.at>=at-360000);captureTargets("BTC",at);for(const s of markets.values())schedule(s.slug)}const becameConnected=!spotConnected;spotConnected=spotReady.has("BTC");if(becameConnected&&spotConnected)state()}catch{}};ws.onerror=()=>{lastError="Chainlink WebSocket error";console.warn(lastError)};ws.onclose=e=>{clearInterval(heartbeat);clearInterval(watchdog);spotSockets.delete(ws);spotReady.clear();spotConnected=false;lastError=`Chainlink WebSocket closed (${e.code}${e.reason?`: ${e.reason}`:""})`;console.warn(lastError);state();reject(new Error(lastError))}});backoff=1000}catch{await sleep(backoff);backoff=Math.min(30000,backoff*2)}}}
setInterval(()=>{for(const s of markets.values())evaluate(s)},1000);
setInterval(()=>{state();snapshot();void settle()},5000);snapshot();await Promise.all([marketLoop(),spotLoop()]);
