import {paperSaleAccounting} from '../lib/paper-accounting.ts';
import {parseSettlementFrame,settlementAnchor,type SettlementPoint} from '../lib/settlement-feed.ts';
import fs from "node:fs";import path from "node:path";
import {openRecoveryDb,migrateRecovery} from "../lib/recovery-db.ts";
import {currentCryptoMarketSlugs} from "../lib/complete-set.ts";
import {fetchBook,fetchEventBySlug,summarizeBook} from "../lib/polymarket.ts";
import {applyMarketFrame,hasUsableAskDepth,parseMarketFrames,type StreamBook} from "../lib/market-stream.ts";
import {simulateBuy,simulateSell} from "../lib/execution.ts";
import {estimateVolatility,type SpotPoint} from "../lib/value-strategy.ts";
import {extractChainlinkPoints,isFeedFresh} from "../lib/recovery-strategy.ts";
import {timeWeightedAverage} from "../lib/v5-selective-strategy.ts";
import {blendedUpProbability,decideV6Entry,orderFlowImbalance,shouldMicroHedge,v6Policy,v61Policy,type V6Duration,type V6Side} from "../lib/v6-strategy.ts";
import {v7AdditionDollars,v7MissingOpeningSides,v7OpeningFillAccepted,v7Policy} from "../lib/v7-strategy.ts";

if((process.env.TRADING_MODE||"paper")!=="paper")throw new Error("Safety lock: V6 is paper-only");
const IS_V7=process.env.V7_ACCUMULATOR==="1",IS_V61=!IS_V7&&process.env.V61_ADAPTIVE==="1",policy=IS_V7?v7Policy:IS_V61?v61Policy:v6Policy,VERSION=IS_V7?"V7":IS_V61?"V6.1":"V6",DB=IS_V7?"v7-accumulator.db":IS_V61?"v61-adaptive.db":"v6-adaptive.db",LABEL=IS_V7?"V7 Balanced Adaptive Accumulator · BTC 5m/15m":`${VERSION} Adaptive Momentum · BTC 5m/15m`,PID=path.join(process.cwd(),IS_V7?"data/v7-accumulator.pid":IS_V61?"data/v61-adaptive.pid":"data/v6-adaptive.pid"),MARKET_WS="wss://ws-subscriptions-clob.polymarket.com/ws/market",CHAINLINK_WS="wss://ws-live-data.polymarket.com",BINANCE_WS="wss://data-stream.binance.vision/ws/btcusdt@aggTrade";
const settlementPoints:SettlementPoint[]=[],verifiedTargets=new Set<string>();
const now=()=>new Date().toISOString(),sleep=(n:number)=>new Promise(r=>setTimeout(r,n));
type Spec={slug:string;market:string;asset:"BTC";minutes:V6Duration;start:number;end:number;up:string;down:string;target?:number;targetDelay?:number};
let running=true,marketConnected=false,chainlinkConnected=false,binanceConnected=false,lastMarket:string|null=null,lastSpot:string|null=null,lastError:string|null=null,marketSocket:WebSocket|null=null;
const sockets=new Set<WebSocket>(),markets=new Map<string,Spec>(),tokens=new Map<string,string>(),books=new Map<string,StreamBook>(),chainlink:SpotPoint[]=[],binance:SpotPoint[]=[],timers=new Map<string,ReturnType<typeof setTimeout>>(),recovering=new Set<string>();
function acquire(){fs.mkdirSync(path.dirname(PID),{recursive:true});try{fs.writeFileSync(PID,String(process.pid),{flag:"wx"})}catch{const prior=Number(fs.readFileSync(PID,"utf8"));try{process.kill(prior,0);throw new Error(`${VERSION} already runs as ${prior}`)}catch(e:any){if(e.message?.startsWith(`${VERSION} already`))throw e;fs.unlinkSync(PID);fs.writeFileSync(PID,String(process.pid),{flag:"wx"})}}}
function release(){try{if(Number(fs.readFileSync(PID,"utf8"))===process.pid)fs.unlinkSync(PID)}catch{}}
function markStopped(){try{const d=db();try{d.prepare("UPDATE stream_state SET status='stopped',market_connected=0,spot_connected=0,last_error=NULL,updated_at=? WHERE id=1").run(now())}finally{d.close()}}catch{}}
function stop(){running=false;markStopped();marketSocket?.close();for(const s of sockets)s.close();for(const t of timers.values())clearTimeout(t);release();setTimeout(()=>process.exit(0),100).unref()}
acquire();process.on("exit",release);process.on("SIGINT",stop);process.on("SIGTERM",stop);migrateRecovery(DB,LABEL);
const db=()=>openRecoveryDb(DB);
function account(d=db()){const start=(d.prepare("SELECT starting_balance FROM account WHERE id=1").get() as any).starting_balance,rows=d.prepare("SELECT * FROM positions").all() as any[];const realized=rows.reduce((s,r)=>s+Number(r.realized_pnl||0),0),deployed=rows.filter(r=>r.status==="open").reduce((s,r)=>s+Number(r.cost),0),unrealized=rows.filter(r=>r.status==="open").reduce((s,r)=>s+Number(r.shares)*Number(r.current_price)-Number(r.cost),0);return {start,realized,deployed,unrealized,equity:start+realized+unrealized,available:start+realized-deployed}}
function snapshot(){const d=db();try{const a=account(d);d.prepare("INSERT INTO snapshots(equity,available_cash,deployed,realized_pnl,unrealized_pnl,captured_at) VALUES(?,?,?,?,?,?)").run(a.equity,a.available,a.deployed,a.realized,a.unrealized,now())}finally{d.close()}}
function state(){const d=db();try{const connected=marketConnected&&chainlinkConnected&&binanceConnected;d.prepare("INSERT INTO stream_state(id,status,market_connected,spot_connected,last_market_message,last_spot_message,subscribed_tokens,last_error,updated_at) VALUES(1,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET status=excluded.status,market_connected=excluded.market_connected,spot_connected=excluded.spot_connected,last_market_message=excluded.last_market_message,last_spot_message=excluded.last_spot_message,subscribed_tokens=excluded.subscribed_tokens,last_error=excluded.last_error,updated_at=excluded.updated_at").run(connected?"connected":"reconnecting",marketConnected?1:0,chainlinkConnected&&binanceConnected?1:0,lastMarket,lastSpot,tokens.size,lastError,now())}finally{d.close()}}
async function discover(){return (await Promise.all(currentCryptoMarketSlugs(Date.now()/1000).filter(x=>x.asset==="BTC").map(async x=>{try{const e=await fetchEventBySlug(x.slug),m=e.markets?.[0];if(!m||e.closed||m.closed)return null;const outcomes=JSON.parse(m.outcomes||"[]"),ids=JSON.parse(m.clobTokenIds||"[]"),u=outcomes.findIndex((v:string)=>/^(up|yes)$/i.test(v)),dn=outcomes.findIndex((v:string)=>/^(down|no)$/i.test(v));if(u<0||dn<0)return null;const old=markets.get(x.slug);return {slug:x.slug,market:e.title||x.slug,asset:"BTC",minutes:x.minutes,start:x.start,end:x.start+x.minutes*60,up:ids[u],down:ids[dn],target:old?.target,targetDelay:old?.targetDelay} as Spec}catch(e){lastError=String(e);return null}}))).filter(Boolean) as Spec[]}
async function refresh(ws:WebSocket,initial=false){const found=await discover();if(!found.length)throw new Error("No current BTC 5m/15m markets");const old=new Set(tokens.keys()),next=new Set(found.flatMap(s=>[s.up,s.down])),d=db();markets.clear();tokens.clear();try{for(const s of found){const saved=d.prepare("SELECT target,target_delay FROM markets WHERE slug=?").get(s.slug) as any;if(saved?.target){s.target=Number(saved.target);s.targetDelay=Number(saved.target_delay)}markets.set(s.slug,s);tokens.set(s.up,s.slug);tokens.set(s.down,s.slug);d.prepare("INSERT INTO markets(slug,market,asset,minutes,start_ts,end_ts,up_token,down_token,target,target_delay,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,NULL,NULL,'active',?,?) ON CONFLICT(slug) DO UPDATE SET updated_at=excluded.updated_at").run(s.slug,s.market,"BTC",s.minutes,s.start,s.end,s.up,s.down,now(),now())}}finally{d.close()}const add=[...next].filter(x=>!old.has(x)),remove=[...old].filter(x=>!next.has(x));if(initial)ws.send(JSON.stringify({assets_ids:[...next],type:"market",custom_feature_enabled:true}));else{if(add.length)ws.send(JSON.stringify({assets_ids:add,operation:"subscribe"}));if(remove.length)ws.send(JSON.stringify({assets_ids:remove,operation:"unsubscribe"}))}for(const s of found)if(!hasUsableAskDepth(books.get(s.up))||!hasUsableAskDepth(books.get(s.down)))void recover(s);console.log(`${VERSION} tracking ${found.map(x=>`${x.minutes}m`).join("+")} (${next.size} tokens)`) }
async function recover(s:Spec){if(recovering.has(s.slug))return;recovering.add(s.slug);try{const [u,d]=await Promise.all([fetchBook(s.up),fetchBook(s.down)]);books.set(s.up,u);books.set(s.down,d);schedule(s.slug)}catch(e){lastError=`Book recovery: ${String(e)}`}finally{recovering.delete(s.slug)}}
function captureTargets(at:number){const d=db();try{for(const m of markets.values()){if(verifiedTargets.has(m.slug))continue;const target=settlementAnchor(settlementPoints,m.start*1000);if(!target)continue;m.target=target;m.targetDelay=0;verifiedTargets.add(m.slug);d.prepare("UPDATE markets SET target=?,target_delay=0,updated_at=? WHERE slug=?").run(target,now(),m.slug);}}finally{d.close()}}

function add(...args:Parameters<typeof addUnchecked>){const d=args[0];d.exec("BEGIN IMMEDIATE");try{const result=addUnchecked(...args);d.exec("COMMIT");return result}catch(e){d.exec("ROLLBACK");throw e}}
function addUnchecked(d:any,s:Spec,side:V6Side,phase:string,fill:any,prob:number,reason:string){const token=side==="Up"?s.up:s.down,stamp=now(),projected=fill.shares-fill.spent,nextId=IS_V7?Number((d.prepare("SELECT COALESCE(MAX(id),0)+1 n FROM actions").get() as any).n):0,eventKey=IS_V7?`${phase}:${s.slug}:${side}:${nextId}`:`${phase}:${s.slug}:${side}`,r=d.prepare("INSERT OR IGNORE INTO actions(event_key,slug,market,phase,outcome,probability,requested,spent,shares,avg_price,fee,fill_ratio,projected_profit,reason,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(eventKey,s.slug,s.market,phase,side,prob,fill.spent,fill.spent,fill.shares,fill.avgPrice,fill.fee,fill.fillRatio,projected,reason,stamp);if(!r.changes)return false;const existing=d.prepare("SELECT * FROM positions WHERE token=? AND status='open'").get(token) as any;if(existing)d.prepare("UPDATE positions SET shares=shares+?,cost=cost+?,current_price=?,updated_at=? WHERE token=?").run(fill.shares,fill.spent,fill.avgPrice,stamp,token);else d.prepare("INSERT INTO positions(token,slug,market,asset,minutes,outcome,shares,cost,current_price,realized_pnl,status,opened_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,0,'open',?,?) ON CONFLICT(token) DO UPDATE SET shares=excluded.shares,cost=excluded.cost,current_price=excluded.current_price,status='open',opened_at=excluded.opened_at,updated_at=excluded.updated_at,closed_at=NULL").run(token,s.slug,s.market,"BTC",s.minutes,side,fill.shares,fill.spent,fill.avgPrice,stamp,stamp);return true}
function recordDecision(d:any,s:Spec,p:any,spot:number,sigma:number,remaining:number,action:string,reason:string){d.prepare("INSERT INTO decisions(slug,winner,probability,up_probability,spot,target,seconds_remaining,volatility,action,reason,projected_profit,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,NULL,?) ON CONFLICT(slug) DO UPDATE SET winner=excluded.winner,probability=excluded.probability,up_probability=excluded.up_probability,spot=excluded.spot,target=excluded.target,seconds_remaining=excluded.seconds_remaining,volatility=excluded.volatility,action=excluded.action,reason=excluded.reason,created_at=excluded.created_at").run(s.slug,p>=.5?"Up":"Down",Math.max(p,1-p),p,spot,s.target||0,remaining,sigma,action,reason,now())}
function tryV7Opening(s:Spec,ub:StreamBook,dbk:StreamBook){const d=db(),remaining=s.end-Date.now()/1000,spot=binance.at(-1)?.price||s.target||0;try{const opening=d.prepare("SELECT outcome FROM actions WHERE slug=? AND phase='opening_pair'").all(s.slug) as any[],missing=v7MissingOpeningSides(opening.map(x=>x.outcome));if(!missing.length)return true;const elapsed=Date.now()/1000-s.start;if(elapsed<0||elapsed>v7Policy.openingWindowSeconds){recordDecision(d,s,.5,spot,0,remaining,"observe",`Opening ${missing.join(" + ")} remained unfilled after ${v7Policy.openingWindowSeconds} seconds; additions disabled`);return false}const today=now().slice(0,10),daily=Number((d.prepare("SELECT COALESCE(SUM(realized_pnl),0) p FROM positions WHERE closed_at LIKE ?").get(`${today}%`) as any).p);if(v7Policy.dailyLossStop!==null&&daily<=-v7Policy.dailyLossStop){recordDecision(d,s,.5,spot,0,remaining,"observe","Daily paper-loss stop reached");return false}const filled:V6Side[]=[],blocked:string[]=[];for(const side of missing){const current=account(d),unix=Date.now()/1000,activeDuration=Number((d.prepare("SELECT COALESCE(SUM(p.cost),0) x FROM positions p JOIN markets m ON m.slug=p.slug WHERE p.status='open' AND p.minutes=? AND m.end_ts>?").get(s.minutes,unix) as any).x),activeCombined=Number((d.prepare("SELECT COALESCE(SUM(p.cost),0) x FROM positions p JOIN markets m ON m.slug=p.slug WHERE p.status='open' AND m.end_ts>?").get(unix) as any).x);if(current.available<v7Policy.openingDollarsPerSide){blocked.push(`${side}: cash`);continue}if(activeDuration+v7Policy.openingDollarsPerSide>v7Policy.maximumOpenExposureByDuration[s.minutes]||activeCombined+v7Policy.openingDollarsPerSide>v7Policy.maximumCombinedExposure){blocked.push(`${side}: active exposure`);continue}const fill=simulateBuy(side==="Up"?ub:dbk,v7Policy.openingDollarsPerSide);if(!v7OpeningFillAccepted(fill.fillRatio)){blocked.push(`${side}: ${(fill.fillRatio*100).toFixed(0)}% depth`);continue}if(add(d,s,side,"opening_pair",fill,.5,"Independent opening leg; spread-neutral retry until paired")){filled.push(side);console.log(`${s.slug}: opened ${side} at $${fill.spent.toFixed(2)}`)}}if(filled.length)snapshot();const remainingMissing=v7MissingOpeningSides((d.prepare("SELECT outcome FROM actions WHERE slug=? AND phase='opening_pair'").all(s.slug) as any[]).map(x=>x.outcome));if(remainingMissing.length)recordDecision(d,s,.5,spot,0,remaining,"fill_wait",`${filled.length?`Filled ${filled.join(" + ")}; `:""}retrying ${remainingMissing.join(" + ")} (${blocked.join(", ")||"book refresh"})`);else recordDecision(d,s,.5,spot,0,remaining,"paper_buy","Both $20 opening legs are filled; adaptive additions unlocked");return false}finally{d.close()}}
function evaluate(s:Spec){const ub=books.get(s.up),dbk=books.get(s.down);if(!hasUsableAskDepth(ub)||!hasUsableAskDepth(dbk)){void recover(s);return}if(IS_V7&&!tryV7Opening(s,ub!,dbk!))return;const settlement=settlementPoints.at(-1);if(!verifiedTargets.has(s.slug)||!settlement||Date.now()-settlement.at>5000||!s.target||binance.length<3){lastError="Waiting for official opening TWAP and fresh reference";return;}lastError=null;const u=summarizeBook(ub!),dn=summarizeBook(dbk!),point=binance.at(-1)!,remaining=s.end-Date.now()/1000,window=binance.filter(x=>x.at>=point.at-(s.minutes===5?180_000:600_000)),sigma=estimateVolatility(window),startPoint=[...binance].reverse().find(x=>x.at<=s.start*1000+3000)||window[0];if(!startPoint||sigma<=0)return;const p30=[...binance].reverse().find(x=>x.at<=point.at-30_000)||window[0],p120=[...binance].reverse().find(x=>x.at<=point.at-120_000)||window[0],m30=Math.log(point.price/p30.price),m120=Math.log(point.price/p120.price),upFlow=orderFlowImbalance(ub!.bids,ub!.asks),downFlow=orderFlowImbalance(dbk!.bids,dbk!.asks),upP=blendedUpProbability({current:settlement.price,target:s.target,secondsRemaining:Math.max(1,remaining),sigma,momentum30:m30,momentum120:m120,upFlow,downFlow,duration:s.minutes}),d=db();try{if(u.bid>0)d.prepare("UPDATE positions SET current_price=?,updated_at=? WHERE token=? AND status='open'").run(u.bid,now(),s.up);if(dn.bid>0)d.prepare("UPDATE positions SET current_price=?,updated_at=? WHERE token=? AND status='open'").run(dn.bid,now(),s.down);const open=d.prepare("SELECT * FROM positions WHERE slug=? AND status='open'").all(s.slug) as any[];
    if(IS_V7){const a=account(d),unix=Date.now()/1000,durationExposure=Number((d.prepare("SELECT COALESCE(SUM(p.cost),0) x FROM positions p JOIN markets m ON m.slug=p.slug WHERE p.status='open' AND p.minutes=? AND m.end_ts>?").get(s.minutes,unix) as any).x),combinedExposure=Number((d.prepare("SELECT COALESCE(SUM(p.cost),0) x FROM positions p JOIN markets m ON m.slug=p.slug WHERE p.status='open' AND m.end_ts>?").get(unix) as any).x),today=now().slice(0,10),daily=Number((d.prepare("SELECT COALESCE(SUM(realized_pnl),0) p FROM positions WHERE closed_at LIKE ?").get(`${today}%`) as any).p);
      const last=d.prepare("SELECT created_at FROM actions WHERE slug=? AND phase='adaptive_accumulation' ORDER BY id DESC LIMIT 1").get(s.slug) as any;if(last&&(Date.now()-Date.parse(last.created_at))/1000<v7Policy.additionCooldownSeconds){recordDecision(d,s,upP,settlement.price,sigma,remaining,"manage","Holding both sides; adaptive-add cooldown active");return}const decision=decideV6Entry({duration:s.minutes,secondsRemaining:remaining,intervalMove:point.price-startPoint.price,upProbability:upP,upAsk:u.ask,downAsk:dn.ask,upSpread:u.spread,downSpread:dn.spread,upFlow,downFlow,availableCash:a.available,durationExposure,combinedExposure,dailyPnl:daily},v7Policy);if(decision.action!=="paper_buy"||decision.probability<v7Policy.minimumProbability){recordDecision(d,s,upP,settlement.price,sigma,remaining,"observe",decision.reason);return}const dollars=Math.min(v7AdditionDollars(decision.probability),a.available,v7Policy.maximumOpenExposureByDuration[s.minutes]-durationExposure,v7Policy.maximumCombinedExposure-combinedExposure);if(dollars<5){recordDecision(d,s,upP,settlement.price,sigma,remaining,"observe","Risk budget or paper cash is below $5");return}const book=decision.side==="Up"?ub!:dbk!,fill=simulateBuy(book,dollars);if(fill.fillRatio<v7Policy.minimumFillRatio){recordDecision(d,s,upP,settlement.price,sigma,remaining,"fill_wait","Visible depth could not fill 95% of adaptive addition");return}if(add(d,s,decision.side,"adaptive_accumulation",fill,decision.probability,`Probability-scaled addition: ${decision.reason}`)){snapshot();recordDecision(d,s,upP,settlement.price,sigma,remaining,"paper_buy",`Added $${fill.spent.toFixed(2)} to ${decision.side}; no selling or hedging`);console.log(`${s.slug}: accumulated ${decision.side} $${fill.spent.toFixed(2)}`)}return}
    if(open.length){for(const held of open){if(held.cost<=policy.microHedgeDollars+.1)continue;const heldP=held.outcome==="Up"?upP:1-upP,book=held.outcome==="Up"?ub!:dbk!,sell=simulateSell(book,held.shares),loss=held.cost>0?(held.cost-sell.proceeds)/held.cost:0,age=(Date.now()-Date.parse(held.opened_at))/1000;if(age>=policy.minimumHoldSeconds&&heldP<policy.exitConfidenceFloor&&loss>=policy.exitLossFraction&&sell.fillRatio>=policy.minimumFillRatio){const accounting=paperSaleAccounting(held.shares,held.cost,sell.shares,sell.proceeds),pnl=accounting.realizedPnl,stamp=now();d.exec("BEGIN IMMEDIATE");try{d.prepare("INSERT OR IGNORE INTO actions(event_key,slug,market,phase,outcome,probability,requested,spent,shares,avg_price,fee,fill_ratio,projected_profit,reason,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(`adaptive_exit:${s.slug}:${held.outcome}:${stamp}`,s.slug,s.market,"adaptive_exit",held.outcome,heldP,held.shares,sell.proceeds,sell.shares,sell.avgPrice,sell.fee,sell.fillRatio,pnl,"Independent signal reversed and executable loss limit confirmed",stamp);d.prepare("UPDATE positions SET shares=?,cost=?,current_price=?,realized_pnl=realized_pnl+?,status=?,updated_at=?,closed_at=? WHERE token=?").run(accounting.remainingShares,accounting.remainingCost,sell.avgPrice,pnl,accounting.closed?"sold":"open",stamp,accounting.closed?stamp:null,held.token);d.exec("COMMIT")}catch(e){d.exec("ROLLBACK");throw e}}}recordDecision(d,s,upP,settlement.price,sigma,remaining,"manage","Continuously recalculating probability and executable exit");return}
    const a=account(d),durationExposure=(d.prepare("SELECT COALESCE(SUM(cost),0) x FROM positions WHERE status='open' AND minutes=?").get(s.minutes) as any).x,today=now().slice(0,10),daily=Number((d.prepare("SELECT COALESCE(SUM(realized_pnl),0) p FROM positions WHERE closed_at LIKE ?").get(`${today}%`) as any).p),decision=decideV6Entry({duration:s.minutes,secondsRemaining:remaining,intervalMove:point.price-startPoint.price,upProbability:upP,upAsk:u.ask,downAsk:dn.ask,upSpread:u.spread,downSpread:dn.spread,upFlow,downFlow,availableCash:a.available,durationExposure:Number(durationExposure),combinedExposure:a.deployed,dailyPnl:daily},policy);
    if(decision.action==="paper_buy"){const book=decision.side==="Up"?ub!:dbk!,fill=simulateBuy(book,decision.dollars);if(fill.fillRatio>=policy.minimumFillRatio&&add(d,s,decision.side,decision.deterministic?"deterministic_momentum":"adaptive_value",fill,decision.probability,decision.reason)){recordDecision(d,s,upP,settlement.price,sigma,remaining,"paper_buy",decision.reason);if(shouldMicroHedge(decision.probability,policy)){const opposite=decision.side==="Up"?"Down":"Up",hf=simulateBuy(opposite==="Up"?ub!:dbk!,Math.min(policy.microHedgeDollars,account(d).available));if(hf.fillRatio>=policy.minimumFillRatio)add(d,s,opposite,"micro_hedge",hf,1-decision.probability,"$2 extreme-skew tail hedge")}snapshot();console.log(`${s.slug}: ${decision.side} $${fill.spent.toFixed(2)} (${decision.reason})`)}else recordDecision(d,s,upP,settlement.price,sigma,remaining,"fill_wait","Visible depth could not fill 95%") }else recordDecision(d,s,upP,settlement.price,sigma,remaining,"observe",decision.reason)
  }finally{d.close()}}
function schedule(slug:string){const old=timers.get(slug);if(old)clearTimeout(old);timers.set(slug,setTimeout(()=>{timers.delete(slug);const s=markets.get(slug);if(s)evaluate(s)},20))}
async function settle(){const d=db(),rows=d.prepare("SELECT * FROM markets WHERE status='active' AND end_ts<?").all(Date.now()/1000-5) as any[];d.close();for(const s of rows)try{const e=await fetchEventBySlug(s.slug),m=e.markets?.[0];if(!e.closed||!m?.closed)continue;const ids=JSON.parse(m.clobTokenIds||"[]"),prices=JSON.parse(m.outcomePrices||"[]"),x=db();try{for(const p of x.prepare("SELECT * FROM positions WHERE slug=? AND status='open'").all(s.slug) as any[]){const i=ids.indexOf(p.token),final=Number(prices[i]);if(i<0||(final!==0&&final!==1))continue;x.prepare("UPDATE positions SET shares=0,cost=0,current_price=?,realized_pnl=realized_pnl+?,status=?,updated_at=?,closed_at=? WHERE token=?").run(final,p.shares*final-p.cost,final===1?"won":"lost",now(),now(),p.token)}x.prepare("UPDATE markets SET status='resolved',updated_at=? WHERE slug=?").run(now(),s.slug)}finally{x.close()}}catch(e){lastError=String(e)}snapshot()}
async function marketLoop(){let delay=1000;while(running){try{await new Promise<void>((_,reject)=>{const ws=new WebSocket(MARKET_WS);marketSocket=ws;let refreshTimer:any,ping:any;ws.onopen=async()=>{try{await refresh(ws,true);marketConnected=true;state();refreshTimer=setInterval(()=>void refresh(ws).catch(e=>lastError=String(e)),5000);ping=setInterval(()=>ws.readyState===1&&ws.send("PING"),10000)}catch(e){reject(e)}};ws.onmessage=e=>{lastMarket=now();if(e.data!=="PONG")for(const frame of parseMarketFrames(String(e.data)))for(const token of applyMarketFrame(books,frame)){const slug=tokens.get(token);if(slug)schedule(slug)}};ws.onclose=()=>{clearInterval(refreshTimer);clearInterval(ping);marketConnected=false;state();reject(new Error("market socket closed"))};ws.onerror=()=>{lastError="Polymarket WebSocket error"}});delay=1000}catch{await sleep(delay);delay=Math.min(30000,delay*2)}}}
async function chainlinkLoop(){let delay=1000;while(running){try{await new Promise<void>((_,reject)=>{const ws=new WebSocket(CHAINLINK_WS);sockets.add(ws);let ping:any,watch:any,last=Date.now();ws.onopen=()=>{ws.send(JSON.stringify({action:"subscribe",subscriptions:[{topic:"crypto_prices_chainlink",type:"update"},{topic:"crypto_prices_twap_sixty",type:"update"}]}));ping=setInterval(()=>ws.readyState===1&&ws.send("PING"),10000);watch=setInterval(()=>{if(!isFeedFresh(last,Date.now()))ws.close()},5000)};ws.onmessage=e=>{if(e.data==="PONG")return;try{const frame=JSON.parse(String(e.data)),twap=parseSettlementFrame(frame);if(twap&&twap.at>(settlementPoints.at(-1)?.at||0)){settlementPoints.push(twap);while(settlementPoints[0]?.at<twap.at-1000000)settlementPoints.shift();last=Date.now();captureTargets(twap.at);}for(const p of extractChainlinkPoints(frame.topic==="crypto_prices_chainlink"?(frame.payload||{}):{}).filter(x=>x.asset==="BTC")){last=Date.now();lastSpot=now();chainlink.push({at:p.at,price:p.price});while(chainlink[0]?.at<p.at-1_000_000)chainlink.shift();captureTargets(p.at)}chainlinkConnected=true;state()}catch{}};ws.onclose=()=>{clearInterval(ping);clearInterval(watch);chainlinkConnected=false;sockets.delete(ws);state();reject(new Error("chainlink closed"))}});delay=1000}catch{await sleep(delay);delay=Math.min(30000,delay*2)}}}
async function binanceLoop(){let delay=1000;while(running){try{await new Promise<void>((_,reject)=>{const ws=new WebSocket(BINANCE_WS);sockets.add(ws);ws.onopen=()=>{binanceConnected=true;state()};ws.onmessage=e=>{try{const x=JSON.parse(String(e.data)),p={at:Number(x.T||Date.now()),price:Number(x.p)};if(p.price>0){binance.push(p);while(binance[0]?.at<p.at-1_000_000)binance.shift();lastSpot=now();for(const s of markets.values())schedule(s.slug)}}catch{}};ws.onclose=()=>{binanceConnected=false;sockets.delete(ws);state();reject(new Error("binance closed"))};ws.onerror=()=>{lastError="Binance public WebSocket error"}});delay=1000}catch{await sleep(delay);delay=Math.min(30000,delay*2)}}}
setInterval(()=>{for(const s of markets.values())evaluate(s)},1000);setInterval(()=>{state();snapshot();void settle()},5000);snapshot();await Promise.all([marketLoop(),chainlinkLoop(),binanceLoop()]);
