import {migrate,openDb} from "../lib/db.ts";
import {currentCryptoMarketSlugs} from "../lib/complete-set.ts";
import {applyMarketFrame,parseMarketFrames,type StreamBook} from "../lib/market-stream.ts";
import {fetchEventBySlug,summarizeBook} from "../lib/polymarket.ts";
import {simulateBuy} from "../lib/execution.ts";
import {decideValueEntry,estimateVolatility,valueStrategyPolicy,type SpotPoint} from "../lib/value-strategy.ts";

if((process.env.TRADING_MODE||"paper")!=="paper")throw new Error("Safety lock: TRADING_MODE must equal paper");
const MARKET_WS="wss://ws-subscriptions-clob.polymarket.com/ws/market",SPOT_WS="wss://ws-live-data.polymarket.com";
const now=()=>new Date().toISOString(),delay=(ms:number)=>new Promise(r=>setTimeout(r,ms));
type Spec={slug:string;market:string;asset:"BTC"|"ETH";minutes:5|15;start:number;end:number;upTokenId:string;downTokenId:string;target?:number;targetDelay?:number};
let running=true,marketSocket:WebSocket|null=null,spotSocket:WebSocket|null=null,marketConnected=false,spotConnected=false,lastMarket:string|null=null,lastSpot:string|null=null,lastError:string|null=null;
const markets=new Map<string,Spec>(),tokenToSlug=new Map<string,string>(),books=new Map<string,StreamBook>(),spotHistory:{BTC:SpotPoint[];ETH:SpotPoint[]}={BTC:[],ETH:[]},timers=new Map<string,ReturnType<typeof setTimeout>>();
process.on("SIGINT",()=>{running=false;marketSocket?.close(1000,"stopped");spotSocket?.close(1000,"stopped")});process.on("SIGTERM",()=>{running=false;marketSocket?.close();spotSocket?.close()});

migrate();{const d=openDb();try{d.prepare("INSERT OR IGNORE INTO pv_account(id,starting_balance,strategy,created_at) VALUES(1,1000,'Price-to-Target Value Lab · BTC/ETH 5m/15m',?)").run(now())}finally{d.close()}}
function account(d:ReturnType<typeof openDb>){const start=(d.prepare("SELECT starting_balance FROM pv_account WHERE id=1").get() as any).starting_balance,rows=d.prepare("SELECT * FROM pv_positions").all() as any[];const realized=rows.reduce((s,r)=>s+Number(r.realized_pnl||0),0),deployed=rows.filter(r=>r.status==="open").reduce((s,r)=>s+Number(r.cost_basis),0),unrealized=rows.filter(r=>r.status==="open").reduce((s,r)=>s+Number(r.shares)*Number(r.current_price)-Number(r.cost_basis),0);return {start,realized,deployed,unrealized,equity:start+realized+unrealized,available:start+realized-deployed}}
function snapshot(){const d=openDb();try{const a=account(d);d.prepare("INSERT INTO pv_snapshots(equity,available_cash,deployed,realized_pnl,unrealized_pnl,captured_at) VALUES(?,?,?,?,?,?)").run(a.equity,a.available,a.deployed,a.realized,a.unrealized,now())}finally{d.close()}}
function state(){const d=openDb();try{d.prepare("INSERT INTO pv_stream_state(id,status,market_connected,spot_connected,last_market_message_at,last_spot_message_at,subscribed_tokens,last_error,updated_at) VALUES(1,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET status=excluded.status,market_connected=excluded.market_connected,spot_connected=excluded.spot_connected,last_market_message_at=excluded.last_market_message_at,last_spot_message_at=excluded.last_spot_message_at,subscribed_tokens=excluded.subscribed_tokens,last_error=excluded.last_error,updated_at=excluded.updated_at").run(marketConnected&&spotConnected?"connected":"reconnecting",marketConnected?1:0,spotConnected?1:0,lastMarket,lastSpot,tokenToSlug.size,lastError,now())}finally{d.close()}}

async function discover(){const targets=currentCryptoMarketSlugs(Math.floor(Date.now()/1000)),found=await Promise.all(targets.map(async t=>{try{const e=await fetchEventBySlug(t.slug),m=e.markets?.[0];if(!m||e.closed||m.closed)return null;const outcomes=JSON.parse(m.outcomes||"[]"),tokens=JSON.parse(m.clobTokenIds||"[]"),ui=outcomes.findIndex((x:string)=>/^(up|yes)$/i.test(x)),di=outcomes.findIndex((x:string)=>/^(down|no)$/i.test(x));if(ui<0||di<0)return null;const old=markets.get(t.slug);return {slug:t.slug,market:e.title||t.slug,asset:t.asset,minutes:t.minutes,start:t.start,end:t.start+t.minutes*60,upTokenId:tokens[ui],downTokenId:tokens[di],target:old?.target,targetDelay:old?.targetDelay} as Spec}catch{return null}}));return found.filter(Boolean) as Spec[]}
async function refresh(ws:WebSocket,initial=false){const found=await discover();if(!found.length)throw new Error("No current short crypto markets");const oldTokens=new Set(tokenToSlug.keys()),nextTokens=new Set(found.flatMap(x=>[x.upTokenId,x.downTokenId]));markets.clear();tokenToSlug.clear();const d=openDb();try{for(const s of found){const saved=d.prepare("SELECT target_price,target_delay_seconds FROM pv_markets WHERE market_slug=?").get(s.slug) as any;if(saved?.target_price){s.target=Number(saved.target_price);s.targetDelay=Number(saved.target_delay_seconds)}markets.set(s.slug,s);tokenToSlug.set(s.upTokenId,s.slug);tokenToSlug.set(s.downTokenId,s.slug);d.prepare("INSERT INTO pv_markets(market_slug,market,asset,minutes,start_ts,end_ts,up_token_id,down_token_id,target_price,target_captured_at,target_delay_seconds,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,NULL,NULL,NULL,'active',?,?) ON CONFLICT(market_slug) DO UPDATE SET updated_at=excluded.updated_at").run(s.slug,s.market,s.asset,s.minutes,s.start,s.end,s.upTokenId,s.downTokenId,now(),now())}}finally{d.close()}const added=[...nextTokens].filter(x=>!oldTokens.has(x)),removed=[...oldTokens].filter(x=>!nextTokens.has(x));if(initial)ws.send(JSON.stringify({assets_ids:[...nextTokens],type:"market",custom_feature_enabled:true}));else{if(added.length)ws.send(JSON.stringify({assets_ids:added,operation:"subscribe"}));if(removed.length)ws.send(JSON.stringify({assets_ids:removed,operation:"unsubscribe"}))}console.log(`Value Lab subscriptions: ${nextTokens.size} tokens`)}

function captureTargets(asset:"BTC"|"ETH",price:number,at:number){const unix=at/1000,d=openDb();try{for(const s of markets.values()){if(s.asset!==asset||s.target||unix<s.start||unix>s.start+valueStrategyPolicy.maximumTargetDelaySeconds)continue;s.target=price;s.targetDelay=unix-s.start;d.prepare("UPDATE pv_markets SET target_price=?,target_captured_at=?,target_delay_seconds=?,updated_at=? WHERE market_slug=?").run(price,new Date(at).toISOString(),s.targetDelay,now(),s.slug);console.log(`${s.slug}: target ${price.toFixed(2)} captured at +${s.targetDelay.toFixed(1)}s`)}}finally{d.close()}}
function evaluate(s:Spec){const upBook=books.get(s.upTokenId),downBook=books.get(s.downTokenId),history=spotHistory[s.asset];if(!upBook||!downBook||!s.target||!history.length)return;const up=summarizeBook(upBook),down=summarizeBook(downBook),point=history.at(-1)!,secondsRemaining=s.end-Date.now()/1000,window=history.filter(x=>x.at>=point.at-120000),sigma=estimateVolatility(window),historySeconds=(point.at-window[0].at)/1000,d=openDb();try{d.prepare("UPDATE pv_positions SET current_price=?,updated_at=? WHERE token_id=? AND status='open'").run(up.bid,now(),s.upTokenId);d.prepare("UPDATE pv_positions SET current_price=?,updated_at=? WHERE token_id=? AND status='open'").run(down.bid,now(),s.downTokenId);const existing=d.prepare("SELECT decision FROM pv_events WHERE market_slug=?").get(s.slug) as any;if(existing?.decision==="paper_buy")return;const a=account(d),today=now().slice(0,10),daily=(d.prepare("SELECT COALESCE(SUM(realized_pnl),0) p FROM pv_positions WHERE closed_at LIKE ?").get(`${today}%`) as any).p,decision=decideValueEntry({minutes:s.minutes,secondsRemaining,targetDelaySeconds:s.targetDelay||0,historySeconds,current:point.price,target:s.target,sigmaPerRootSecond:sigma,upAsk:up.ask,downAsk:down.ask,upSpread:up.spread,downSpread:down.spread,availableCash:a.available,dailyRealizedPnl:Number(daily)}),stamp=now();let filled=0,shares=0,avg=0,fee=0,ratio=0,outcome:string|null=null;if(decision.action==="paper_buy"){outcome=decision.side;const token=outcome==="Up"?s.upTokenId:s.downTokenId,fill=simulateBuy(outcome==="Up"?upBook:downBook,decision.dollars);filled=fill.spent;shares=fill.shares;avg=fill.avgPrice;fee=fill.fee;ratio=fill.fillRatio;if(filled>=5&&ratio>=.9)d.prepare("INSERT INTO pv_positions(token_id,market_slug,market,asset,minutes,outcome,shares,cost_basis,current_price,realized_pnl,status,opened_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,0,'open',?,?)").run(token,s.slug,s.market,s.asset,s.minutes,outcome,shares,filled,avg,stamp,stamp);else{filled=0;shares=0}}
    const isBuy=filled>=5;d.prepare("INSERT INTO pv_events(market_slug,market,asset,minutes,outcome,target_price,spot_price,seconds_remaining,volatility,fair_probability,market_ask,net_edge,requested_dollars,filled_dollars,shares,avg_price,fee_usdc,fill_ratio,decision,reason,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(market_slug) DO UPDATE SET outcome=excluded.outcome,target_price=excluded.target_price,spot_price=excluded.spot_price,seconds_remaining=excluded.seconds_remaining,volatility=excluded.volatility,fair_probability=excluded.fair_probability,market_ask=excluded.market_ask,net_edge=excluded.net_edge,requested_dollars=excluded.requested_dollars,filled_dollars=excluded.filled_dollars,shares=excluded.shares,avg_price=excluded.avg_price,fee_usdc=excluded.fee_usdc,fill_ratio=excluded.fill_ratio,decision=excluded.decision,reason=excluded.reason,created_at=excluded.created_at").run(s.slug,s.market,s.asset,s.minutes,outcome,s.target,point.price,secondsRemaining,sigma,decision.action==="paper_buy"?decision.probability:null,decision.action==="paper_buy"?decision.ask:null,decision.action==="paper_buy"?decision.netEdge:null,decision.action==="paper_buy"?decision.dollars:0,filled,shares,avg,fee,ratio,isBuy?"paper_buy":"observe",isBuy?decision.reason:decision.action==="paper_buy"?"Visible depth could not fill 90%":decision.reason,stamp);if(isBuy){console.log(`${s.slug}: value ${outcome} $${filled.toFixed(2)} at ${(avg*100).toFixed(1)}¢`);snapshot()}}finally{d.close()}}
function schedule(slug:string){const old=timers.get(slug);if(old)clearTimeout(old);timers.set(slug,setTimeout(()=>{timers.delete(slug);const s=markets.get(slug);if(s)evaluate(s)},50))}
async function settle(){const d=openDb();try{for(const s of d.prepare("SELECT * FROM pv_markets WHERE status='active' AND end_ts<?").all(Date.now()/1000-5) as any[]){try{const e=await fetchEventBySlug(s.market_slug),m=e.markets?.[0];if(!e.closed||!m?.closed)continue;const tokens=JSON.parse(m.clobTokenIds||"[]"),prices=JSON.parse(m.outcomePrices||"[]");for(const p of d.prepare("SELECT * FROM pv_positions WHERE market_slug=? AND status='open'").all(s.market_slug) as any[]){const i=tokens.indexOf(p.token_id),final=Number(prices[i]);if(i<0||(final!==0&&final!==1))continue;d.prepare("UPDATE pv_positions SET shares=0,cost_basis=0,current_price=?,realized_pnl=realized_pnl+?,status=?,updated_at=?,closed_at=? WHERE token_id=?").run(final,p.shares*final-p.cost_basis,final===1?"won":"lost",now(),now(),p.token_id)}d.prepare("UPDATE pv_markets SET status='resolved',updated_at=? WHERE market_slug=?").run(now(),s.market_slug)}catch{}}}finally{d.close()}snapshot()}

async function marketLoop(){let backoff=1000;while(running){try{await new Promise<void>(async(resolve,reject)=>{const ws=new WebSocket(MARKET_WS);marketSocket=ws;let refreshTimer:any,heartbeat:any;ws.onopen=async()=>{try{await refresh(ws,true);marketConnected=true;lastError=null;state();refreshTimer=setInterval(()=>void refresh(ws),15000);heartbeat=setInterval(()=>ws.readyState===WebSocket.OPEN&&ws.send("PING"),10000)}catch(e){reject(e)}};ws.onmessage=e=>{lastMarket=now();if(e.data!=="PONG")for(const frame of parseMarketFrames(String(e.data)))for(const token of applyMarketFrame(books,frame)){const slug=tokenToSlug.get(token);if(slug)schedule(slug)}};ws.onerror=()=>{lastError="Market WebSocket error"};ws.onclose=()=>{clearInterval(refreshTimer);clearInterval(heartbeat);marketConnected=false;state();reject(new Error("market socket closed"))}});backoff=1000}catch{await delay(backoff);backoff=Math.min(30000,backoff*2)}}}
async function spotLoop(){let backoff=1000;while(running){try{await new Promise<void>((resolve,reject)=>{const ws=new WebSocket(SPOT_WS);spotSocket=ws;let heartbeat:any;ws.onopen=()=>{spotConnected=true;lastError=null;state();ws.send(JSON.stringify({action:"subscribe",subscriptions:[{topic:"crypto_prices_chainlink",type:"update"}]}));heartbeat=setInterval(()=>ws.readyState===WebSocket.OPEN&&ws.send("PING"),10000)};ws.onmessage=e=>{if(e.data==="PONG")return;try{const m=JSON.parse(String(e.data)),p=m.payload||{},symbol=String(p.symbol||"").toLowerCase(),asset=symbol==="btc/usd"?"BTC":symbol==="eth/usd"?"ETH":null,price=Number(p.value),at=Number(p.timestamp||Date.now());if(!asset||price<=0)return;lastSpot=now();const h=spotHistory[asset];h.push({at,price});spotHistory[asset]=h.filter(x=>x.at>=at-180000);captureTargets(asset,price,at);for(const s of markets.values())if(s.asset===asset)schedule(s.slug)}catch{}};ws.onerror=()=>{lastError="Spot WebSocket error"};ws.onclose=()=>{clearInterval(heartbeat);spotConnected=false;state();reject(new Error("spot socket closed"))}});backoff=1000}catch{await delay(backoff);backoff=Math.min(30000,backoff*2)}}}
setInterval(()=>{state();snapshot();void settle()},10000);snapshot();await Promise.all([marketLoop(),spotLoop()]);
