import {DatabaseSync} from "node:sqlite";import fs from "node:fs";import path from "node:path";
export function openRecoveryDb(fileName=process.env.RECOVERY_DB_FILE||"recoverybot.db"){const dir=path.join(process.cwd(),"data");fs.mkdirSync(dir,{recursive:true});const d=new DatabaseSync(path.join(dir,fileName));d.exec("PRAGMA busy_timeout=5000; PRAGMA foreign_keys=ON;");return d}
export function migrateRecovery(fileName=process.env.RECOVERY_DB_FILE||"recoverybot.db",strategyName?:string){const d=openRecoveryDb(fileName);d.exec(`
CREATE TABLE IF NOT EXISTS account(id INTEGER PRIMARY KEY CHECK(id=1),starting_balance REAL NOT NULL,strategy TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS markets(slug TEXT PRIMARY KEY,market TEXT NOT NULL,asset TEXT NOT NULL,minutes INTEGER NOT NULL,start_ts INTEGER NOT NULL,end_ts INTEGER NOT NULL,up_token TEXT NOT NULL,down_token TEXT NOT NULL,target REAL,target_delay REAL,status TEXT NOT NULL DEFAULT 'active',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS actions(id INTEGER PRIMARY KEY AUTOINCREMENT,event_key TEXT UNIQUE NOT NULL,slug TEXT NOT NULL,market TEXT NOT NULL,phase TEXT NOT NULL,outcome TEXT NOT NULL,probability REAL,requested REAL NOT NULL,spent REAL NOT NULL,shares REAL NOT NULL,avg_price REAL NOT NULL,fee REAL NOT NULL,fill_ratio REAL NOT NULL,projected_profit REAL,reason TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS positions(token TEXT PRIMARY KEY,slug TEXT NOT NULL,market TEXT NOT NULL,asset TEXT NOT NULL,minutes INTEGER NOT NULL,outcome TEXT NOT NULL,shares REAL NOT NULL,cost REAL NOT NULL,current_price REAL NOT NULL,realized_pnl REAL NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'open',opened_at TEXT NOT NULL,updated_at TEXT NOT NULL,closed_at TEXT);
CREATE TABLE IF NOT EXISTS decisions(slug TEXT PRIMARY KEY,winner TEXT NOT NULL,probability REAL NOT NULL,up_probability REAL NOT NULL,spot REAL NOT NULL,target REAL NOT NULL,seconds_remaining REAL NOT NULL,volatility REAL NOT NULL,action TEXT NOT NULL,reason TEXT NOT NULL,projected_profit REAL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS snapshots(id INTEGER PRIMARY KEY AUTOINCREMENT,equity REAL NOT NULL,available_cash REAL NOT NULL,deployed REAL NOT NULL,realized_pnl REAL NOT NULL,unrealized_pnl REAL NOT NULL,captured_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS stream_state(id INTEGER PRIMARY KEY CHECK(id=1),status TEXT NOT NULL,market_connected INTEGER NOT NULL DEFAULT 0,spot_connected INTEGER NOT NULL DEFAULT 0,last_market_message TEXT,last_spot_message TEXT,subscribed_tokens INTEGER NOT NULL DEFAULT 0,last_error TEXT,updated_at TEXT NOT NULL);
`);const version=process.env.RECOVERY_VERSION,label=strategyName||(version==="v3-original"?"Original Profitable-Era V3 · BTC/ETH 5m":version==="v3"?"Balanced Recovery Decider V3 · BTC/ETH 5m":"Balanced Recovery Decider V4 · BTC/ETH 5m");d.prepare("INSERT OR IGNORE INTO account(id,starting_balance,strategy,created_at) VALUES(1,1000,?,?)").run(label,new Date().toISOString());d.close()}
export function recoveryQuery<T>(sql:string,params:any[]=[],fileName="recoverybot.db",strategyName?:string){migrateRecovery(fileName,strategyName);const d=openRecoveryDb(fileName);try{return d.prepare(sql).all(...params) as T[]}finally{d.close()}}
export function recoveryV3Query<T>(sql:string,params:any[]=[]){return recoveryQuery<T>(sql,params,"recovery-v3.db")}
export function recoveryOriginalV3Query<T>(sql:string,params:any[]=[]){return recoveryQuery<T>(sql,params,"recovery-v3-original.db","Original Profitable-Era V3 · BTC/ETH 5m")}
export function selectiveV5Query<T>(sql:string,params:any[]=[]){return recoveryQuery<T>(sql,params,"v5-selective.db","Selective Value V5 · BTC/ETH 5m")}
export function dynamicV51Query<T>(sql:string,params:any[]=[]){return recoveryQuery<T>(sql,params,"v51-dynamic.db","V5.1 Dynamic Value · BTC 5m")}
export function dynamicV52Query<T>(sql:string,params:any[]=[]){return recoveryQuery<T>(sql,params,"v52-dynamic.db","V5.2 Active Dynamic Value · BTC 5m")}
export function scaledV53Query<T>(sql:string,params:any[]=[]){return recoveryQuery<T>(sql,params,"v53-scaled.db","V5.3 Scaled Active · BTC 5m")}
export function adaptiveV6Query<T>(sql:string,params:any[]=[]){return recoveryQuery<T>(sql,params,"v6-adaptive.db","V6 Adaptive Momentum · BTC 5m/15m")}
export function adaptiveV61Query<T>(sql:string,params:any[]=[]){return recoveryQuery<T>(sql,params,"v61-adaptive.db","V6.1 Adaptive Momentum · BTC 5m/15m")}
export function accumulatorV7Query<T>(sql:string,params:any[]=[]){return recoveryQuery<T>(sql,params,"v7-accumulator.db","V7 Balanced Adaptive Accumulator · BTC 5m/15m")}
