// Immutable profitable-era V3 reference. Do not edit this file when experimenting.
import {simulateBuy} from "./execution.ts";
import {probabilityAboveTarget} from "./value-strategy.ts";
export {extractChainlinkPoints,isFeedFresh,missingOpeningSides} from "./recovery-strategy.ts";

type Book={bids:{price:string;size:string}[];asks:{price:string;size:string}[]};

export const originalV3Policy={
  version:"v3-original",
  independentOpening:false,
  openingDollarsPerSide:5,
  openingRetrySeconds:30,
  observationSeconds:150,
  decisionGraceSeconds:20,
  minimumWinnerProbability:.50,
  lateMarketProbability:.85,
  targetProfit:1,
  maxRecoveryDollars:25,
  maxLateAddDollars:10,
  maxMarketCost:45,
  maxPortfolioExposure:1000,
  minimumFillRatio:.90
} as const;

export function isOriginalV3HalfwayDecisionTime(minutes:number,elapsedSeconds:number){
  return minutes===5&&elapsedSeconds>=originalV3Policy.observationSeconds&&elapsedSeconds<=originalV3Policy.observationSeconds+originalV3Policy.decisionGraceSeconds;
}

export function chooseOriginalV3Winner(input:{current:number;target:number;secondsRemaining:number;sigmaPerRootSecond:number}){
  const up=probabilityAboveTarget(input.current,input.target,input.secondsRemaining,input.sigmaPerRootSecond);
  return {side:(up>=.5?"Up":"Down") as "Up"|"Down",probability:Math.max(up,1-up),upProbability:up};
}

export function sizeOriginalV3Recovery(input:{book:Book;existingWinnerShares:number;totalMarketCost:number;availableCash:number;currentMarketCost:number;maxAdditionalDollars?:number}){
  const p=originalV3Policy,currentProjected=input.existingWinnerShares-input.totalMarketCost;
  if(currentProjected>=p.targetProfit)return {action:"skip" as const,reason:`The selected side already projects at least $${p.targetProfit.toFixed(2)} profit`};
  const cap=Math.min(input.maxAdditionalDollars??p.maxRecoveryDollars,input.availableCash,p.maxMarketCost-input.currentMarketCost);
  if(cap<5)return {action:"skip" as const,reason:"Less than $5 remained inside the recovery cap"};
  for(let budget=5;budget<=cap+1e-9;budget+=.25){
    const fill=simulateBuy(input.book,budget),projectedProfit=input.existingWinnerShares+fill.shares-input.totalMarketCost-fill.spent;
    if(fill.fillRatio>=p.minimumFillRatio&&projectedProfit>=p.targetProfit)return {action:"buy" as const,budget,fill,projectedProfit,reason:`Smallest visible-depth fill targeting $${p.targetProfit.toFixed(2)} profit if the selected side wins`};
  }
  return {action:"skip" as const,reason:`Recovery required more than the $${cap.toFixed(2)} safety cap`};
}
