import {simulateBuy} from "./execution.ts";
import {probabilityAboveTarget} from "./value-strategy.ts";
export {extractChainlinkPoints,isFeedFresh,missingOpeningSides} from "./recovery-strategy.ts";
type Book={bids:{price:string;size:string}[];asks:{price:string;size:string}[]};
export const recoveryPolicy={version:"v3",independentOpening:false,openingDollarsPerSide:100,openingRetrySeconds:60,observationSeconds:150,decisionGraceSeconds:20,minimumWinnerProbability:.70,minimumProbabilityEdge:.08,lateConfirmationEnabled:false,lateMarketProbability:.85,targetProfit:10,maxRecoveryDollars:200,maxLateAddDollars:0,maxMarketCost:400,maxPortfolioExposure:600,maxOpeningWorstCaseLoss:10,minimumEquityToTrade:650,minimumFillRatio:.99} as const;
export function isHalfwayDecisionTime(minutes:number,elapsedSeconds:number){return minutes===5&&elapsedSeconds>=recoveryPolicy.observationSeconds&&elapsedSeconds<=recoveryPolicy.observationSeconds+recoveryPolicy.decisionGraceSeconds}
export function chooseLateWinner(input:{current:number;target:number;secondsRemaining:number;sigmaPerRootSecond:number}){const up=probabilityAboveTarget(input.current,input.target,input.secondsRemaining,input.sigmaPerRootSecond);return {side:(up>=.5?"Up":"Down") as "Up"|"Down",probability:Math.max(up,1-up),upProbability:up}}
export function recoveryBudgetForProbability(probability:number){return recoveryPolicy.maxRecoveryDollars*(probability>=.90?1:.5)}
export function sizeRecoveryBuy(input:{book:Book;existingWinnerShares:number;totalMarketCost:number;availableCash:number;currentMarketCost:number;maxAdditionalDollars?:number;modelProbability?:number}){
  const p=recoveryPolicy,currentProjected=input.existingWinnerShares-input.totalMarketCost;if(currentProjected>=p.targetProfit)return {action:"skip" as const,reason:`The selected side already projects at least $${p.targetProfit.toFixed(2)} profit`};
  const cap=Math.min(input.maxAdditionalDollars??p.maxRecoveryDollars,input.availableCash,p.maxMarketCost-input.currentMarketCost);if(cap<5)return {action:"skip" as const,reason:"Less than $5 remained inside the recovery cap"};
  for(let budget=5;budget<=cap+1e-9;budget+=.25){const fill=simulateBuy(input.book,budget),projectedProfit=input.existingWinnerShares+fill.shares-input.totalMarketCost-fill.spent,effectivePrice=fill.shares?fill.spent/fill.shares:1,hasEdge=input.modelProbability==null||input.modelProbability-effectivePrice>=p.minimumProbabilityEdge;if(fill.fillRatio>=p.minimumFillRatio&&projectedProfit>=p.targetProfit&&hasEdge)return {action:"buy" as const,budget,fill,projectedProfit,reason:`Smallest visible-depth fill targeting $${p.targetProfit.toFixed(2)} profit with at least ${(p.minimumProbabilityEdge*100).toFixed(0)} points of executable probability edge`}}
  return {action:"skip" as const,reason:`No addition inside the $${cap.toFixed(2)} cap produced both $${p.targetProfit.toFixed(2)} projected profit and ${(p.minimumProbabilityEdge*100).toFixed(0)} points of executable edge`};
}
