import {selectiveV5Query as query} from "../../lib/recovery-db";
import ValueVisuals from "../value/value-visuals";
export const dynamic="force-dynamic";
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(n);
export default function SelectiveV5Page(){
  const account=query<any>("SELECT * FROM account WHERE id=1")[0]||{starting_balance:1000},snapshots=query<any>("SELECT equity,available_cash,deployed,captured_at FROM (SELECT id,equity,available_cash,deployed,captured_at FROM snapshots ORDER BY id DESC LIMIT 240) ORDER BY id").map(x=>({...x})),snap=snapshots.at(-1)||{equity:1000,available_cash:1000,deployed:0},state=query<any>("SELECT * FROM stream_state WHERE id=1")[0],actions=query<any>("SELECT * FROM actions ORDER BY id DESC LIMIT 100"),decisions=query<any>("SELECT * FROM decisions ORDER BY created_at DESC LIMIT 100"),positions=query<any>("SELECT * FROM positions ORDER BY updated_at DESC LIMIT 100"),open=positions.filter((p:any)=>p.status==="open"),resolvedSlugs=new Set(positions.filter((p:any)=>p.status!=="open").map((p:any)=>p.slug)),marketPnl=[...resolvedSlugs].map(slug=>positions.filter((p:any)=>p.slug===slug).reduce((sum:number,p:any)=>sum+p.realized_pnl,0)),wins=marketPnl.filter(x=>x>0).length,pnl=snap.equity-account.starting_balance,directional=actions.filter((a:any)=>a.phase==="directional"),completeSets=new Set(actions.filter((a:any)=>a.phase==="complete_set").map((a:any)=>a.slug)).size;
  return <main><header><div><span className="eyebrow">PAPER-ONLY · SELECTIVE VALUE V5</span><h1>Selective Value <i>V5</i></h1><p>BTC five-minute only · halfway directional decision every market · realistic executable fills.</p><a className="bot-switch" href="/recovery">View preserved Original V3 →</a></div><div className={`status ${state?.status||"starting"}`}><span/> {state?.market_connected&&state?.spot_connected?"BOTH FEEDS CONNECTED":"STARTING"} · PAPER ONLY</div></header>
  <section className="hero"><div><small>Paper account equity</small><strong className={pnl>=0?"positive":"negative"}>{money(snap.equity)}</strong><em>{money(pnl)} P&amp;L · fresh $1,000 ledger</em></div><div><small>Available cash</small><strong>{money(snap.available_cash)}</strong><em>{money(snap.deployed)} deployed</em></div><div><small>Directional fills</small><strong>{directional.length}</strong><em>one side only · $10 maximum</em></div><div><small>Complete sets</small><strong>{completeSets}</strong><em>equal shares · positive locked edge</em></div><div><small>Resolved</small><strong>{marketPnl.length}</strong><em>{wins} profitable markets</em></div></section>
  <ValueVisuals snapshots={snapshots} startingBalance={account.starting_balance}/>
  <section className="event-ledger"><div className="section-title"><div><small>DECISION JOURNAL</small><h2>Every trade must clear its costs</h2></div><span>{decisions.length} evaluated markets</span></div>{decisions.map((d:any)=><div className="event-row v5-row" key={d.slug}><mark className={d.action.startsWith("paper_")?"buy":"observe"}>{d.action==="paper_complete_set"?"BOTH":d.winner}</mark><div><b>{d.slug}</b><small>Fair chance {(d.probability*100).toFixed(1)}% · target {d.target.toFixed(2)} · spot {d.spot.toFixed(2)} · {Math.max(0,d.seconds_remaining).toFixed(0)}s left</small><small>{d.reason}</small></div><div><small>Action</small><b>{d.action.replaceAll("_"," ").toUpperCase()}</b></div><div><small>Volatility</small><b>{(d.volatility*100).toFixed(3)}%</b></div><div><small>Projected</small><b>{d.projected_profit==null?"—":money(d.projected_profit)}</b></div></div>)}{!decisions.length&&<div className="empty-state"><b>Collecting clean market evidence.</b><span>V5 waits until the halfway window and is allowed to remain in cash.</span></div>}</section>
  <section className="event-ledger"><div className="section-title"><div><small>PAPER EXECUTION LEDGER</small><h2>Qualified fills</h2></div><span>{actions.length} legs</span></div>{actions.map((a:any)=><div className="event-row v5-row" key={a.id}><mark className="buy">{a.phase}</mark><div><b>{a.market} · {a.outcome}</b><small>{a.reason}</small><small>{(a.fill_ratio*100).toFixed(0)}% depth fill · {money(a.fee)} fee</small></div><div><small>Cost</small><b>{money(a.spent)}</b></div><div><small>Shares</small><b>{a.shares.toFixed(2)}</b></div><div><small>Average</small><b>{(a.avg_price*100).toFixed(1)}¢</b></div></div>)}{!actions.length&&<div className="empty-state"><b>No qualifying fill yet.</b><span>Skipping an overpriced market is part of the strategy.</span></div>}</section>
  <section className="mirror-positions"><div className="section-title"><div><small>PAPER BOOK</small><h2>Positions and settlements</h2></div><span>{open.length} open</span></div>{positions.map((p:any)=><div className="trade" key={p.token}><div><b>{p.market} · {p.outcome}</b><small>{p.asset} 5m · {p.shares.toFixed(2)} shares · {money(p.cost)} cost · {(p.current_price*100).toFixed(1)}¢ executable mark · {p.status.toUpperCase()}</small></div><strong className={p.status==="open"?"":p.realized_pnl>=0?"positive":"negative"}>{p.status==="open"?money(p.shares*p.current_price):money(p.realized_pnl)}</strong></div>)}</section>
  <section className="grid"><article><div className="section-title"><div><small>01 / DIRECTIONAL</small><h2>Every-market direction</h2></div></div><div className="note"><b>No positive-edge threshold</b><p>At halfway, V5 chooses the side with the higher Chainlink-based probability and attempts a $10 paper purchase even when its calculated edge is negative.</p></div><div className="note"><b>Real fills still required</b><p>The local order book must provide an executable ask and at least 95% of the requested paper depth. A missing market cannot be fabricated.</p></div></article><article><div className="section-title"><div><small>02 / NON-DIRECTIONAL</small><h2>Complete-set exception</h2></div></div><div className="note"><b>Equal shares—not equal dollars</b><p>V5 buys both outcomes only when their combined visible cost, taker fees, and execution reserve remain below the guaranteed $1 settlement.</p></div><div className="note"><b>Risk limits</b><p>$25 maximum complete set, $100 maximum open exposure, and a $300 daily realized-loss stop.</p></div></article></section><footer><span>SELECTIVE VALUE V5</span><span>BTC · 5M · FRESH $1,000 · ZERO EXECUTION</span></footer></main>
}
