import {adaptiveV6Query as q} from "../../lib/recovery-db";import {v6Policy as p} from "../../lib/v6-strategy";import {displayStreamStatus,streamStatusLabel} from "../../lib/stream-health";import "./v6.css";
export const dynamic="force-dynamic";
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(n||0);
function Path({values}:{values:number[]}){if(values.length<2)return null;const lo=Math.min(...values),hi=Math.max(...values),range=hi-lo||1,d=values.map((v,i)=>`${i?"L":"M"} ${(i/(values.length-1))*100} ${34-((v-lo)/range)*30}`).join(" ");return <svg viewBox="0 0 100 38" preserveAspectRatio="none"><path d={d}/></svg>}
export default function V6(){const account=q<any>("SELECT * FROM account WHERE id=1")[0]||{starting_balance:1000},snaps=q<any>("SELECT * FROM snapshots ORDER BY id DESC LIMIT 240").reverse(),snap=snaps.at(-1)||{equity:1000,available_cash:1000,deployed:0,realized_pnl:0,unrealized_pnl:0},state=q<any>("SELECT * FROM stream_state WHERE id=1")[0],displayStatus=displayStreamStatus(state),actions=q<any>("SELECT * FROM actions ORDER BY id DESC LIMIT 80"),decisions=q<any>("SELECT d.*,m.minutes FROM decisions d LEFT JOIN markets m ON m.slug=d.slug ORDER BY d.created_at DESC LIMIT 40"),positions=q<any>("SELECT * FROM positions ORDER BY updated_at DESC LIMIT 60"),resolved=positions.filter((x:any)=>["won","lost","sold"].includes(x.status)),wins=resolved.filter((x:any)=>x.realized_pnl>0).length,pnl=snap.equity-account.starting_balance,active=decisions[0],by5=resolved.filter((x:any)=>x.minutes===5),by15=resolved.filter((x:any)=>x.minutes===15),sum=(xs:any[])=>xs.reduce((s,x)=>s+Number(x.realized_pnl||0),0);return <main className="v6-shell">
  <header className="v6-head"><div><span className="eyebrow">PAPER RESEARCH · THREE LIVE DATA FEEDS</span><h1>Adaptive <i>Pulse</i> V6</h1><p>BTC 5-minute + 15-minute · target-distance probability · momentum · flow · visible liquidity.</p></div><div className={`status ${displayStatus}`}><span/> {streamStatusLabel(displayStatus)}</div></header>
  <section className="v6-kpis"><div className="primary"><small>Paper equity</small><strong className={pnl>=0?"positive":"negative"}>{money(snap.equity)}</strong><em>{money(pnl)} total P&amp;L</em></div><div><small>Available</small><strong>{money(snap.available_cash)}</strong><em>{money(snap.deployed)} at risk</em></div><div><small>Realized</small><strong>{money(snap.realized_pnl)}</strong><em>{money(snap.unrealized_pnl)} open</em></div><div><small>Win rate</small><strong>{resolved.length?Math.round(wins/resolved.length*100):0}%</strong><em>{wins}/{resolved.length} closed legs</em></div><div><small>Tracked</small><strong>{state?.subscribed_tokens||0}</strong><em>outcome books</em></div></section>
  <section className="v6-grid"><article className="chart-card"><div className="card-head"><div><small>ACCOUNT PATH</small><h2>Equity trajectory</h2></div><b>{snaps.length} samples</b></div><Path values={snaps.map((x:any)=>x.equity)}/><div className="chart-scale"><span>{money(Math.min(...snaps.map((x:any)=>x.equity),1000))}</span><span>Now {money(snap.equity)}</span></div></article>
  <article className="radar"><small>LIVE DECISION ENGINE</small><h2>{active?`${active.minutes}m · ${active.winner}`:"Collecting signal"}</h2><div className="prob"><span style={{width:`${(active?.up_probability||.5)*100}%`}}>UP {Math.round((active?.up_probability||.5)*100)}%</span><b>DOWN {Math.round((1-(active?.up_probability||.5))*100)}%</b></div><dl><div><dt>BTC spot</dt><dd>{active?.spot?.toFixed(2)||"—"}</dd></div><div><dt>Target</dt><dd>{active?.target?.toFixed(2)||"—"}</dd></div><div><dt>Time left</dt><dd>{active?`${Math.max(0,active.seconds_remaining).toFixed(0)}s`:"—"}</dd></div></dl><p>{active?.reason||"Waiting for the first synchronized market and price samples."}</p></article>
  <article className="split"><small>TIMEFRAME SCORECARD</small><h2>5m vs 15m</h2><div><span><b>5 minute</b><i>{by5.length} closed</i></span><strong className={sum(by5)>=0?"positive":"negative"}>{money(sum(by5))}</strong></div><div><span><b>15 minute</b><i>{by15.length} closed</i></span><strong className={sum(by15)>=0?"positive":"negative"}>{money(sum(by15))}</strong></div><p>The ledgers are separated; cross-horizon momentum only adjusts probability.</p></article></section>
  <section className="strategy-strip"><div><small>01</small><b>Observe continuously</b><span>Distance + volatility</span></div><i>→</i><div><small>02</small><b>Confirm executable edge</b><span>Spread + depth + fees</span></div><i>→</i><div><small>03</small><b>Momentum override</b><span>$70 move near 2m</span></div><i>→</i><div><small>04</small><b>Protect capital</b><span>Exit only on reversal</span></div></section>
  <section className="v6-ledger"><div className="card-head"><div><small>DECISION TAPE</small><h2>What the bot sees</h2></div><b>updates every second</b></div>{decisions.map((d:any)=><div className="v6-row" key={d.slug}><mark className={d.action.includes("buy")?"trade":"watch"}>{d.action.replaceAll("_"," ")}</mark><div><b>BTC {d.minutes}m · {d.winner}</b><span>{d.reason}</span></div><strong>{(d.probability*100).toFixed(1)}%</strong><span>{Math.max(0,d.seconds_remaining).toFixed(0)}s</span></div>)}</section>
  <section className="v6-bottom"><article><div className="card-head"><div><small>EXECUTIONS</small><h2>Paper fills</h2></div><b>{actions.length}</b></div>{actions.slice(0,20).map((a:any)=><div className="compact" key={a.id}><span><b>{a.outcome} · {a.phase.replaceAll("_"," ")}</b><small>{a.market}</small></span><strong>{money(a.spent)}</strong></div>)}</article><article><div className="card-head"><div><small>EXPERIMENT PANEL</small><h2>Active thresholds</h2></div><b>edit in code</b></div><div className="thresholds">{Object.entries(p).filter(([,v])=>typeof v==="number"||typeof v==="boolean").map(([k,v])=><div key={k}><span>{k.replaceAll(/([A-Z])/g," $1")}</span><b>{String(v)}</b></div>)}</div></article></section>
  <footer><span>V6 · PAPER ONLY · NO WALLET OR LIVE ORDERS</span><span>Last engine update {state?.updated_at?new Date(state.updated_at).toLocaleTimeString():"—"}</span></footer>
  </main>}
