import {queryAll} from "../../lib/db";
import ValueVisuals from "./value-visuals";
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(n);
export const dynamic="force-dynamic";
export default function ValuePage(){
  const account=queryAll<any>("SELECT * FROM pv_account WHERE id=1")[0]||{starting_balance:1000},snapshots=queryAll<any>("SELECT equity,available_cash,deployed,captured_at FROM (SELECT id,equity,available_cash,deployed,captured_at FROM pv_snapshots ORDER BY id DESC LIMIT 240) ORDER BY id ASC").map(row=>({...row})),snap=snapshots.at(-1)||{equity:1000,available_cash:1000,deployed:0},fullSnap=queryAll<any>("SELECT * FROM pv_snapshots ORDER BY id DESC LIMIT 1")[0]||{realized_pnl:0,unrealized_pnl:0},stream=queryAll<any>("SELECT * FROM pv_stream_state WHERE id=1")[0],events=queryAll<any>("SELECT * FROM pv_events ORDER BY created_at DESC LIMIT 100"),positions=queryAll<any>("SELECT * FROM pv_positions ORDER BY updated_at DESC LIMIT 100"),targets=queryAll<any>("SELECT * FROM pv_markets ORDER BY start_ts DESC LIMIT 8");
  const buys=events.filter((e:any)=>e.decision==="paper_buy"),open=positions.filter((p:any)=>p.status==="open"),pnl=snap.equity-account.starting_balance,captured=targets.filter((t:any)=>t.target_price!=null).length;
  return <main><header><div><span className="eyebrow">SEPARATE PAPER STRATEGY · TWO LIVE EVIDENCE FEEDS</span><h1>Price-to-Target <i>Value Lab</i></h1><p>Independent distance, time and volatility pricing for BTC and ETH · 5-minute and 15-minute markets.</p><a className="bot-switch" href="/hedged">← Hedged Momentum archive</a></div><div className={`status ${stream?.status||"starting"}`}><span/> {stream?.market_connected&&stream?.spot_connected?"BOTH FEEDS CONNECTED":"FEEDS STARTING"} · PAPER ONLY</div></header>
    <section className="hero"><div><small>Paper account equity</small><strong className={pnl>=0?"positive":"negative"}>{money(snap.equity)}</strong><em>{money(pnl)} P&amp;L · separate $1,000 ledger</em></div><div><small>Available cash</small><strong>{money(snap.available_cash)}</strong><em>{money(snap.deployed)} deployed</em></div><div><small>Paper entries</small><strong>{buys.length}</strong><em>{events.length-buys.length} markets waiting</em></div><div><small>Open positions</small><strong>{open.length}</strong><em>held to settlement</em></div><div><small>Live evidence</small><strong>{Number(Boolean(stream?.market_connected))+Number(Boolean(stream?.spot_connected))} / 2</strong><em>order book · Chainlink spot</em></div></section>
    <ValueVisuals snapshots={snapshots} startingBalance={account.starting_balance}/>
    <section className="target-board"><div className="section-title"><div><small>LIVE MARKET MAP</small><h2>Targets and readiness</h2></div><span>{captured} clean starts captured</span></div><div className="target-grid">{targets.slice(0,4).map((t:any)=><article className={`target-card ${t.target_price?"ready":"waiting"}`} key={t.market_slug}><div><small>{t.asset} · {t.minutes} MINUTE</small><b>{t.target_price?t.target_price.toLocaleString(undefined,{maximumFractionDigits:2}):"Awaiting boundary"}</b></div><span>{t.target_price?`READY · +${t.target_delay_seconds.toFixed(1)}S CAPTURE`:"SKIPPING CURRENT MARKET"}</span></article>)}</div></section>
    <section className="event-ledger"><div className="section-title"><div><small>VALUE DECISION JOURNAL</small><h2>Every buy must earn its place</h2></div><span>{buys.length} paper entries</span></div>{events.map((e:any)=><div className="event-row v5-row" key={e.market_slug}><mark className={e.decision==="paper_buy"?"buy":"observe"}>{e.decision==="paper_buy"?"BUY":"WAIT"}</mark><div><b>{e.market}{e.outcome?` · ${e.outcome}`:""}</b><small>{e.asset} {e.minutes}m · target {e.target_price?.toFixed(2)} · spot {e.spot_price?.toFixed(2)} · {Math.max(0,e.seconds_remaining).toFixed(0)}s left</small><small>{e.reason}</small></div><div><small>Fair chance</small><b>{e.fair_probability==null?"—":`${(e.fair_probability*100).toFixed(1)}%`}</b></div><div><small>Net edge</small><b>{e.net_edge==null?"—":`${(e.net_edge*100).toFixed(1)}%`}</b></div><div><small>Paper fill</small><b>{money(e.filled_dollars)}</b></div></div>)}{!events.length&&<div className="empty-state"><b>Waiting for the first evidence-qualified decision.</b><span>The bot is collecting clean start targets and will not manufacture a trade.</span></div>}</section>
    <section className="mirror-positions"><div className="section-title"><div><small>MARK-TO-MARKET PAPER BOOK</small><h2>Positions and settled outcomes</h2></div><span>{open.length} open</span></div>{positions.map((p:any)=><div className="trade" key={p.token_id}><div><b>{p.market} · {p.outcome}</b><small>{p.asset} {p.minutes}m · {p.shares.toFixed(2)} shares · {money(p.cost_basis)} cost · {(p.current_price*100).toFixed(1)}¢ executable mark · {p.status.toUpperCase()}</small></div><strong className={p.status==="open"?"":p.realized_pnl>=0?"positive":"negative"}>{p.status==="open"?money(p.shares*p.current_price):money(p.realized_pnl)}</strong></div>)}{!positions.length&&<div className="empty-state"><b>No position is a valid position.</b><span>Capital remains available until price-to-target evidence clears every guardrail.</span></div>}</section>
    <section className="grid"><article><div className="section-title"><div><small>01 / INDEPENDENT EVIDENCE</small><h2>What creates a signal</h2></div></div><div className="note"><b>Distance × time × volatility</b><p>A move far beyond the target with little time remaining can create conviction; noisy movement near the target cannot.</p></div><div className="note"><b>Polymarket is the price—not the prediction</b><p>The order book supplies the executable ask. Chainlink evidence supplies the independent fair probability.</p></div></article><article><div className="section-title"><div><small>02 / EXECUTION DISCIPLINE</small><h2>What it refuses</h2></div></div><div className="note"><b>6% minimum net edge</b><p>The advantage must survive taker fees, a 1-cent execution reserve, and a maximum 6-cent spread.</p></div><div className="note"><b>Small and measurable</b><p>One $10 paper entry per market, at least 30 seconds of spot history, visible-depth simulation, and a $25 daily realized-loss stop.</p></div></article></section>
    <section className="report"><small>LIVE VALUE BRIEF</small><pre>{`Paper funding basis: ${money(account.starting_balance)}\nPaper equity: ${money(snap.equity)}\nAvailable cash: ${money(snap.available_cash)}\nRealized P&L: ${money(fullSnap.realized_pnl||0)}\nUnrealized P&L: ${money(fullSnap.unrealized_pnl||0)}\nClean targets in recent view: ${captured}\nEvidence-qualified entries: ${buys.length}\nOrder-book feed: ${stream?.market_connected?"connected":"waiting"}\nChainlink spot feed: ${stream?.spot_connected?"connected":"waiting"}\nSafety: deterministic paper simulation; no real orders.`}</pre></section><footer><span>PRICE-TO-TARGET VALUE LAB / V1</span><span>BTC + ETH · 5M + 15M · ZERO EXECUTION</span></footer>
  </main>
}
