"use client";
import {useEffect} from "react";
import {useRouter} from "next/navigation";
type Snapshot={equity:number;available_cash:number;deployed:number;captured_at:string};
export default function ValueVisuals({snapshots,startingBalance}:{snapshots:Snapshot[];startingBalance:number}){
  const router=useRouter();useEffect(()=>{const timer=window.setInterval(()=>router.refresh(),10000);return()=>window.clearInterval(timer)},[router]);
  const points=snapshots.length?snapshots:[{equity:startingBalance,available_cash:startingBalance,deployed:0,captured_at:new Date().toISOString()}],values=points.map(p=>p.equity),min=Math.min(...values,startingBalance-1),max=Math.max(...values,startingBalance+1),range=Math.max(1,max-min),polyline=points.map((p,i)=>`${20+(i/Math.max(1,points.length-1))*760},${170-((p.equity-min)/range)*130}`).join(" "),latest=points.at(-1)!;
  return <><section className="visual-grid"><article className="chart-panel"><div className="section-title"><div><small>LIVE PAPER EQUITY · AUTO-REFRESH 10S</small><h2>Account path</h2></div><span>{points.length} snapshots</span></div><svg className="equity-chart" viewBox="0 0 800 200" role="img" aria-label="Price-to-Target paper equity over time"><line x1="20" y1="170" x2="780" y2="170"/><line x1="20" y1="40" x2="20" y2="170"/><polyline points={polyline}/><text x="26" y="34">${max.toFixed(2)}</text><text x="26" y="188">${min.toFixed(2)}</text></svg></article><article className="allocation"><div className="section-title"><div><small>CAPITAL ALLOCATION</small><h2>Where the ${startingBalance.toLocaleString()} sits</h2></div></div><div className="allocation-track"><span style={{width:`${Math.min(100,latest.deployed/Math.max(1,startingBalance)*100)}%`}}/></div><div className="allocation-key"><span>Deployed <b>${latest.deployed.toFixed(2)}</b></span><span>Available <b>${latest.available_cash.toFixed(2)}</b></span></div><details><summary>Strategy followed</summary><ol><li>Capture BTC or ETH from the Chainlink feed at a clean market boundary.</li><li>Measure the live distance from target and the remaining time.</li><li>Estimate volatility from recent independent spot-price changes.</li><li>Calculate a fair Up or Down probability.</li><li>Require 6% net edge after taker fees and a 1-cent reserve.</li><li>Simulate visible order-book depth and risk at most $10 once per market.</li></ol></details></article></section><section className="strategy-flow"><div><b>CAPTURE TARGET</b><small>Clean Chainlink boundary</small></div><i>→</i><div><b>MEASURE MOVE</b><small>Distance · time · volatility</small></div><i>→</i><div><b>PRICE FAIR ODDS</b><small>Independent probability</small></div><i>→</i><div><b>BUY OR WAIT</b><small>6% net edge required</small></div></section></>
}
