import {DatabaseSync} from 'node:sqlite';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {stripTypeScriptTypes} from 'node:module';
import {paperSaleAccounting} from '../lib/paper-accounting.ts';
const src=fs.readFileSync(new URL('../scripts/v6-stream.ts',import.meta.url),'utf8');
const body=src.slice(src.indexOf('function add('),src.indexOf('function recordDecision'));
const add=new Function('IS_V7','now',stripTypeScriptTypes(body)+';return add;')(false,()=>new Date().toISOString());
const d=new DatabaseSync(':memory:');
d.exec(`CREATE TABLE actions(id INTEGER PRIMARY KEY,event_key TEXT UNIQUE,slug,market,phase,outcome,probability,requested,spent,shares,avg_price,fee,fill_ratio,projected_profit,reason,created_at);CREATE TABLE positions(token TEXT PRIMARY KEY,slug,market,asset,minutes,outcome,shares REAL,cost REAL,current_price REAL,realized_pnl REAL,status,opened_at,updated_at,closed_at);`);
const spec={slug:'s',market:'m',up:'u',down:'d',minutes:5};const fill={shares:50,spent:35,avgPrice:.7,fee:0,fillRatio:1};
assert.equal(add(d,spec,'Up','adaptive_value',fill,.9,'test'),true);
assert.equal(add(d,spec,'Up','adaptive_value',fill,.9,'test'),false);assert.equal(d.prepare('select cost from positions').get().cost,35);
d.exec("UPDATE positions SET shares=0,cost=0,realized_pnl=-26.87,status='sold',closed_at='yesterday'");
add(d,spec,'Up','micro_hedge',{...fill,shares:10,spent:2},.1,'test');let p=d.prepare('select * from positions').get();assert.equal(p.realized_pnl,-26.87);assert.equal(p.closed_at,null);assert.equal(p.cost,2);
add(d,spec,'Up','another',{...fill,shares:5,spent:1},.1,'test');p=d.prepare('select * from positions').get();assert.equal(p.shares,15);assert.equal(p.cost,3);assert.equal(p.realized_pnl,-26.87);
assert.deepEqual(paperSaleAccounting(100,50,95,38),{realizedPnl:-9.5,remainingShares:5,remainingCost:2.5,closed:false});
assert.deepEqual(paperSaleAccounting(5,2.5,5,4),{realizedPnl:1.5,remainingShares:0,remainingCost:0,closed:true});
assert.throws(()=>paperSaleAccounting(5,2,6,3));
d.exec("CREATE TRIGGER fail_position BEFORE INSERT ON positions WHEN NEW.token='d' BEGIN SELECT RAISE(ABORT,'test failure'); END;");assert.throws(()=>add(d,spec,'Down','adaptive_value',fill,.9,'test'));assert.equal(d.prepare("select count(*) n from actions where outcome='Down'").get().n,0);
console.log('PASS: duplicate protection, reopening preserves P&L, accumulation, partial sale, final sale, invalid sale, atomic rollback');
