import {accumulatorV7Query as q} from "../../lib/recovery-db";
import {v7Policy as p} from "../../lib/v7-strategy";
import {displayStreamStatus,streamStatusLabel} from "../../lib/stream-health";
import "../v6/v6.css";
import "./v7.css";

export const dynamic="force-dynamic";
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(n||0));
function Line({values}:{values:number[]}){if(values.length<2)return <div className="empty-chart">Collecting account samples…</div>;const lo=Math.min(...values),hi=Math.max(...values),range=hi-lo||1,d=values.map((v,i)=>`${i?"L":"M"} ${(i/(values.length-1))*100} ${36-((v-lo)/range)*32}`).join(" ");return <svg className="line" viewBox="0 0 100 40" preserveAspectRatio="none"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#7af4cf" stopOpacity=".34"/><stop offset="1" stopColor="#7af4cf" stopOpacity="0"/></linearGradient></defs><path className="area" d={`${d} L 100 40 L 0 40 Z`}/><path d={d}/></svg>}
function Bars({rows}:{rows:any[]}){const peak=Math.max(1,...rows.map(x=>Math.abs(Number(x.pnl))));return <div className="pnl-bars">{rows.map((x,i)=><div className="pnl-bar" key={`${x.slug}-${i}`} title={`${x.minutes}m ${money(x.pnl)}`}><span className={x.pnl>=0?"gain":"loss"} style={{height:`${Math.max(5,Math.abs(x.pnl)/peak*82)}%`}}/><small>{x.minutes}m</small></div>)}</div>}

export default function V7(){
 const account=q<any>("SELECT * FROM account WHERE id=1")[0]||{starting_balance:1000},snaps=q<any>("SELECT * FROM snapshots ORDER BY id DESC LIMIT 240").reverse(),snap=snaps.at(-1)||{equity:1000,available_cash:1000,deployed:0,realized_pnl:0,unrealized_pnl:0},state=q<any>("SELECT * FROM stream_state WHERE id=1")[0],status=displayStreamStatus(state),positions=q<any>("SELECT * FROM positions ORDER BY updated_at DESC LIMIT 80"),actions=q<any>("SELECT * FROM actions ORDER BY id DESC LIMIT 30"),decisions=q<any>("SELECT d.*,m.minutes FROM decisions d LEFT JOIN markets m ON m.slug=d.slug ORDER BY d.created_at DESC LIMIT 24"),recent=q<any>("SELECT p.slug,p.minutes,SUM(p.realized_pnl) pnl,MAX(p.closed_at) closed_at FROM positions p WHERE p.status IN ('won','lost') GROUP BY p.slug,p.minutes ORDER BY closed_at DESC LIMIT 20").reverse(),closed=positions.filter((x:any)=>["won","lost"].includes(x.status)),wins=closed.filter((x:any)=>x.realized_pnl>0).length,pnl=snap.equity-account.starting_balance,active=decisions[0],open=positions.filter((x:any)=>x.status==="open"),upCost=open.filter((x:any)=>x.outcome==="Up").reduce((s:number,x:any)=>s+Number(x.cost),0),downCost=open.filter((x:any)=>x.outcome==="Down").reduce((s:number,x:any)=>s+Number(x.cost),0),by5=closed.filter((x:any)=>x.minutes===5).reduce((s:number,x:any)=>s+Number(x.realized_pnl),0),by15=closed.filter((x:any)=>x.minutes===15).reduce((s:number,x:any)=>s+Number(x.realized_pnl),0),total=Math.max(1,Math.abs(by5)+Math.abs(by15));
 return <main className="v6-shell v7-shell">
  <header className="v6-head"><div><span className="eyebrow">PAPER RESEARCH · BUY-ONLY ACCUMULATION</span><h1>Balanced <i>Conviction</i> V7</h1><p>Open both sides · accumulate the probabilistic leader · hold every share to settlement.</p></div><div className={`status ${status}`}><span/> {streamStatusLabel(status)}</div></header>
  <section className="v6-kpis"><div className="primary"><small>Paper equity</small><strong className={pnl>=0?"positive":"negative"}>{money(snap.equity)}</strong><em>{money(pnl)} total P&amp;L</em></div><div><small>Available</small><strong>{money(snap.available_cash)}</strong><em>{money(snap.deployed)} deployed</em></div><div><small>Realized</small><strong>{money(snap.realized_pnl)}</strong><em>{money(snap.unrealized_pnl)} open</em></div><div><small>Win rate</small><strong>{closed.length?Math.round(wins/closed.length*100):0}%</strong><em>{wins}/{closed.length} closed legs</em></div><div><small>Live books</small><strong>{state?.subscribed_tokens||0}</strong><em>outcome tokens</em></div></section>
  <section className="v7-top"><article className="chart-card"><div className="card-head"><div><small>EQUITY CURVE</small><h2>Account trajectory</h2></div><b>{snaps.length} samples</b></div><Line values={snaps.map((x:any)=>Number(x.equity))}/><div className="chart-scale"><span>{money(Math.min(1000,...snaps.map((x:any)=>x.equity)))}</span><span>Now {money(snap.equity)}</span></div></article>
  <article><div className="card-head"><div><small>RECENT MARKET P&amp;L</small><h2>Outcome rhythm</h2></div><b>{recent.length} markets</b></div><Bars rows={recent}/><div className="legend"><span><i className="gain"/> Profit</span><span><i className="loss"/> Loss</span></div></article>
  <article className="signal"><small>LIVE CONVICTION</small><h2>{active?`BTC ${active.minutes}m · ${active.winner}`:"Synchronizing"}</h2><div className="prob"><span style={{width:`${(active?.up_probability||.5)*100}%`}}>UP {Math.round((active?.up_probability||.5)*100)}%</span><b>DOWN {Math.round((1-(active?.up_probability||.5))*100)}%</b></div><div className="signal-grid"><span>Spot<b>{active?.spot?.toFixed(2)||"—"}</b></span><span>Target<b>{active?.target?.toFixed(2)||"—"}</b></span><span>Remaining<b>{active?`${Math.max(0,active.seconds_remaining).toFixed(0)}s`:"—"}</b></span></div><p>{active?.reason||"Waiting for synchronized market data."}</p></article></section>
  <section className="v7-mid"><article><small>OPEN CAPITAL BALANCE</small><h2>Where accumulation sits</h2><div className="donut-wrap"><div className="donut" style={{background:`conic-gradient(#7af4cf 0 ${snap.deployed?upCost/snap.deployed*100:50}%,#ffae73 0)`}}><b>{money(snap.deployed)}</b><span>deployed</span></div><div className="donut-key"><span><i className="up"/>Up {money(upCost)}</span><span><i className="down"/>Down {money(downCost)}</span><span><i className="cash"/>Cash {money(snap.available_cash)}</span></div></div></article><article><small>TIMEFRAME CONTRIBUTION</small><h2>5m versus 15m</h2><div className="horizon"><div><span>BTC 5 minute</span><b>{money(by5)}</b><i><em style={{width:`${Math.abs(by5)/total*100}%`}}/></i></div><div><span>BTC 15 minute</span><b>{money(by15)}</b><i><em style={{width:`${Math.abs(by15)/total*100}%`}}/></i></div></div></article><article><small>BUY-ONLY SAFETY</small><h2>Execution contract</h2><ul><li><b>$20 + $20</b> independently filled opening legs</li><li><b>60 seconds</b> to retry only the missing side</li><li><b>30 seconds</b> between additions</li><li><b>No additions</b> until both opening legs fill</li><li><b>No sells</b>, reversals, or hedges</li></ul></article></section>
  <section className="strategy-strip"><div><small>01</small><b>Open both outcomes</b><span>Equal $20 paper buys</span></div><i>→</i><div><small>02</small><b>Observe continuously</b><span>Distance + volatility + flow</span></div><i>→</i><div><small>03</small><b>Scale conviction</b><span>$20–$35 additions</span></div><i>→</i><div><small>04</small><b>Hold everything</b><span>Settlement only</span></div></section>
  <section className="v6-ledger"><div className="card-head"><div><small>DECISION TAPE</small><h2>Why V7 acts—or waits</h2></div><b>live</b></div>{decisions.map((d:any)=><div className="v6-row" key={d.slug}><mark className={d.action.includes("buy")?"trade":"watch"}>{d.action.replaceAll("_"," ")}</mark><div><b>BTC {d.minutes}m · {d.winner}</b><span>{d.reason}</span></div><strong>{(d.probability*100).toFixed(1)}%</strong><span>{Math.max(0,d.seconds_remaining).toFixed(0)}s</span></div>)}</section>
  <section className="v6-bottom"><article><div className="card-head"><div><small>ACCUMULATION LEDGER</small><h2>Latest paper buys</h2></div><b>{actions.length}</b></div>{actions.slice(0,16).map((a:any)=><div className="compact" key={a.id}><span><b>{a.outcome} · {a.phase.replaceAll("_"," ")}</b><small>{a.market}</small></span><strong>{money(a.spent)}</strong></div>)}</article><article><div className="card-head"><div><small>ACTIVE PARAMETERS</small><h2>Experiment controls</h2></div><b>{p.version}</b></div><div className="thresholds">{Object.entries(p).filter(([,v])=>typeof v==="number"||typeof v==="boolean").map(([k,v])=><div key={k}><span>{k.replaceAll(/([A-Z])/g," $1")}</span><b>{String(v)}</b></div>)}</div></article></section>
  <footer><span>V7 · PAPER ONLY · NO WALLET OR LIVE ORDERS</span><span>Last update {state?.updated_at?new Date(state.updated_at).toLocaleTimeString():"—"}</span></footer>
 </main>
}
