import {dynamicV51Query as query} from "../../lib/recovery-db";
export const dynamic="force-dynamic";
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(n);
export default function V51Page(){
  const account=query<any>("SELECT * FROM account WHERE id=1")[0]||{starting_balance:1000},snap=query<any>("SELECT * FROM snapshots ORDER BY id DESC LIMIT 1")[0]||{equity:1000,available_cash:1000,deployed:0},state=query<any>("SELECT * FROM stream_state WHERE id=1")[0],actions=query<any>("SELECT * FROM actions ORDER BY id DESC LIMIT 100"),decisions=query<any>("SELECT * FROM decisions ORDER BY created_at DESC LIMIT 100"),positions=query<any>("SELECT * FROM positions ORDER BY updated_at DESC LIMIT 100"),pnl=snap.equity-account.starting_balance;
  return <main><header><div><span className="eyebrow">PAPER-ONLY · DYNAMIC VALUE</span><h1>Dynamic Value <i>V5.1</i></h1><p>Selective bargain entries · momentum and order-flow adjustment · second-by-second exit and safe-hedge tests.</p><a className="bot-switch" href="/v5">View V5 →</a></div><div className={`status ${state?.status||"starting"}`}><span/> {state?.market_connected&&state?.spot_connected?"BOTH FEEDS CONNECTED":"STARTING"} · PAPER ONLY</div></header>
  <section className="hero"><div><small>Paper equity</small><strong className={pnl>=0?"positive":"negative"}>{money(snap.equity)}</strong><em>{money(pnl)} P&amp;L · separate $1,000 ledger</em></div><div><small>Available cash</small><strong>{money(snap.available_cash)}</strong><em>{money(snap.deployed)} deployed</em></div><div><small>Entries</small><strong>{actions.filter((a:any)=>a.phase==="directional").length}</strong><em>3pp executable edge required</em></div><div><small>Dynamic exits</small><strong>{actions.filter((a:any)=>a.phase==="dynamic_exit").length}</strong><em>sold only at visible bids</em></div><div><small>Safe hedges</small><strong>{actions.filter((a:any)=>a.phase==="dynamic_hedge").length}</strong><em>worst-case loss must improve</em></div></section>
  <section className="event-ledger"><div className="section-title"><div><small>DECISION JOURNAL</small><h2>Signal and execution verdicts</h2></div><span>{decisions.length} markets</span></div>{decisions.map((d:any)=><div className="event-row v5-row" key={d.slug}><mark className={d.action.startsWith("paper_")?"buy":"observe"}>{d.winner}</mark><div><b>{d.slug}</b><small>Probability {(d.probability*100).toFixed(1)}% · {Math.max(0,d.seconds_remaining).toFixed(0)}s left</small><small>{d.reason}</small></div><div><small>Action</small><b>{d.action.replaceAll("_"," ").toUpperCase()}</b></div><div><small>Target</small><b>{d.target.toFixed(2)}</b></div><div><small>Spot</small><b>{d.spot.toFixed(2)}</b></div></div>)}</section>
  <section className="event-ledger"><div className="section-title"><div><small>EXECUTION LEDGER</small><h2>Entries, exits, and hedges</h2></div><span>{actions.length} actions</span></div>{actions.map((a:any)=><div className="event-row v5-row" key={a.id}><mark className="buy">{a.phase}</mark><div><b>{a.market} · {a.outcome}</b><small>{a.reason}</small></div><div><small>Value</small><b>{money(a.spent)}</b></div><div><small>Shares</small><b>{a.shares.toFixed(2)}</b></div><div><small>Fill</small><b>{(a.fill_ratio*100).toFixed(0)}%</b></div></div>)}</section>
  <section className="mirror-positions"><div className="section-title"><div><small>PAPER BOOK</small><h2>Positions</h2></div><span>{positions.filter((p:any)=>p.status==="open").length} open</span></div>{positions.map((p:any)=><div className="trade" key={p.token}><div><b>{p.market} · {p.outcome}</b><small>{p.status.toUpperCase()} · {p.shares.toFixed(2)} shares · {money(p.cost)} cost</small></div><strong>{p.status==="open"?money(p.shares*p.current_price):money(p.realized_pnl)}</strong></div>)}</section></main>
}
